### ISSUE TITLE
gnatmake missing in gnat-10, gnatmake-10 exists

### ISSUE THREAD

**Issue by umarcor** [its-pointless/gcc_termux#100]
When `gnat-10` is installed in a clean termux environment, gnatmake-10 exists, but `gnatmake` is missing. Executing `setupgcc-10` does NOT fix it.

Creating a symbolic link is a possible workaround (ghdl/ghdl#1459). However, it would be useful to have it generated automatically. 

In fact, this request is similar to its-pointless/gcc_termux#84. Note that shared libs are correctly linked with gnat-10; this is a different symlink.

**Comment by BenjaminRenz** [comment]
Hi,
starting from a clean enviroment i had to execute:

ln -s $PREFIX/bin/gnatmake-10 $PREFIX/bin/gnatmake
ln -s $PREFIX/bin/gnatbind-10 $PREFIX/bin/gnatbind
ln -s $PREFIX/bin/gnatlink-10 $PREFIX/bin/gnatlink

as an workaround. Strangely there are files in this directory named 'gnatmake-','gnatbind-' ,... with the added hyphen, not sure about those, as they seem to point to the correct location.

**Comment by umarcor** [comment]
It seems that `setup-pathforgcc` fixed the issue.
