### ISSUE TITLE
issue with multiple definitions of ioctl

### ISSUE THREAD

**Issue by BenjaminRenz** [its-pointless/gcc_termux#102]
Hi, while trying to build gnat on termux I encountered an issue inside the file:
'/data/data/com.termux/files/usr/include/bits/ioctl.h'

The original thread is here https://github.com/ghdl/ghdl/pull/1459. 
Here is the log output from termux.sh 2> log.txt

here gnatlink is gnatlink-10
```
gnatlink ghdl_llvm.ali -g grt-cstdio.o
In file included from /data/data/com.termux/files/usr/include/unistd.h:38,
                 from /data/data/com.termux/files/home/ghdl/build-termux/../src/grt/config/times.c:27:
/data/data/com.termux/files/usr/include/bits/ioctl.h:60:5: error: conflicting types for 'ioctl'
   60 | int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
      |     ^~~~~
/data/data/com.termux/files/usr/include/bits/ioctl.h:43:5: note: previous declaration of 'ioctl' was here
   43 | int ioctl(int __fd, int __request, ...);
      |     ^~~~~
In file included from /data/data/com.termux/files/usr/include/sys/times.h:36,
                 from /data/data/com.termux/files/home/ghdl/build-termux/../src/grt/config/times.c:26:
/data/data/com.termux/files/usr/include/bits/ioctl.h:60:80: error: expected ',' or ';' before '__asm__'
   60 | int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
      |                                                                                ^~~~~~~~
make: *** [../src/grt/Makefile.inc:174: times.o] Error 1
```

The file is ioctl.h contains the same code as:
https://android.googlesource.com/platform/bionic/+/master/libc/include/bits/ioctl.h
where comments in the code describe possible workarounds for signeness problems.

This issue seems to be present in the android ndk in other projects aswell:
https://github.com/mono/mono/pull/15650

I'm not really sure if this is the right place to ask this question, so please let me know if this issue should be forwarded to the Android ndk or anywhere else.
Thanks for looking into it.

**Comment by its-pointless** [comment]
the command 
setup-patchforgcc
will fix it. As this script will patch the headers.

**Comment by BenjaminRenz** [comment]
thanks, that worked.
