### ISSUE TITLE
How to install rJava in termux? how to  create java env for R in termux ?

### ISSUE THREAD

**Issue by leechaowen** [its-pointless/gcc_termux#103]
Could someone tell me how to install rJava in termux once R installed in termux? some R packages depend  on java env, but termux could not install JDK. is there has another sulution create java env for R in termux ?Thanks your greate support.

**Comment by hnmn** [comment]
[openjdk 11](https://github.com/Lzhiyong/termux-ndk/releases/download/openjdk-11.0.1/openjdk-11.0.1.tar.xz) 

try this openjdk.
i don't know about rjava but here is jdk i khow.

**Comment by leechaowen** [comment]
Please close this issue. There has openjdk for termux now. run command
pkg search openjdk
pkg install openjdk-17
