### ISSUE TITLE
Supported emulations: `elf_i386 elf_iamcu` in `gfortran/ld`

### ISSUE THREAD

**Issue by RalfWerner** [its-pointless/gcc_termux#104]
Example to repeat (without problems on armv7 and aarch64 devices but also with resetting `ld` and `*/lib/libbfd-2.34.so`):
`printf "%s\n" '      print*,"moin"' '      end'>check.f;gfortran check.f`
since the last update (`pkg in make gcc-8 libgfortan5 ...` and `setupclang-gfort-8`) i got the error:
```
/data/data/com.termux/files/usr/bin/ld: unrecognized emulation mode: -dynamic-linker
Supported emulations: elf_i386 elf_iamcu
collect2: error: ld returned 1 exit status
```
The use of `gcc` (also with `ld`) is problem-free. Is there a simple solution (config) to be successful on _**all devices?**_

**Comment by its-pointless** [comment]
it fails with gcc-8 but works with gcc-10.

**Comment by RalfWerner** [comment]
> im kind of dropping gcc-8 support anyway.

Ok with gcc-10 I had other problems`*)` but none with _**gcc-9**_, so I use _**this**_ - thanks so far. 
`*)` If I have a comprehensible example I will contact you again
