### ISSUE TITLE
FORTIFY: %n not allowed on Android

### ISSUE THREAD

**Issue by Strahinja** [its-pointless/gcc_termux#105]
Some programs, including **groff**(1) and my own C program [**slweb**(1)][1] (which works on my PC but not in Termux under Android) don't seem to work properly on latest Termux with the latest version of this repo applied. After some output, they print the message `FORTIFY: %n not allowed on Android` and abort. For example:
```
$ groff <<<"Hello"
%!PS-Adobe-3.0
%%Creator: groff version 1.22.4
%%CreationDate: Wed Jan 13 16:57:12 2021
%%DocumentNeededResources: font Times-Roman
FORTIFY: %n not allowed on Android
FORTIFY: %n not allowed on Android
Aborted
$
```
After posting a comment in the [similar issue thread][2] on Termux' repo, I was told to report it here. as apparently it was fixed in Termux itself.

[1]: https://github.com/Strahinja/slweb
[2]: https://github.com/termux/termux-packages/issues/4381#issuecomment-759228533

**Comment by easyaspi314** [comment]
This is due to a bug in vasnprintf.c in older versions of Gnulib. I might throw together a patch later today.

**Comment by its-pointless** [comment]
should be fixed

**Comment by Strahinja** [comment]
It works now after updating, thanks. 👍
