### ISSUE TITLE
R execution error maybe d/t libicu version mismatching (v.68)

### ISSUE THREAD

**Issue by TimelessConsistence** [its-pointless/gcc_termux#106]
Dear Dr. Anderson, and colleague managers:

Thank you for your dedications for this repository. 
My issue report is on the R execution error on Termux. I tried to install R and libicu on Termux (F-droid download) of my mobile phone (android 10). The libicu installation was confined to version 68. R did not work with following error:
`> R
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library "libicuuc.so.67" not found

I found very similar error was discussed AUG 2020 with libicu version 67. Please check and solve this issue!  Thank you again for your efforts and dedications !

**Comment by yeyuan98** [comment]
Same issue here, it would be very helpful if this can be solved. Thanks!

**Comment by sacrrie** [comment]
Hear hear. Hope maintainer can solve this issue soon. Thank you all for your great work!

**Comment by TimelessConsistence** [comment]
Thank you so much for your rapid solving this issue!
Termux r-base v.4.0.3-1 update solved this issue nicely. Have a nice day!

**Comment by TimelessConsistence** [comment]
I think above mentioned issue may be automatically solved when the other users would update their r-base version maintained properly. So I close this issue. Thank you again dear colleague managers!
