### ISSUE TITLE
Mongodb libicudata.so.67 not found

### ISSUE THREAD

**Issue by anang42429** [its-pointless/gcc_termux#109]
After updating libicu to version 68, mongodb no longer work

![Screenshot_20210216-123458](https://user-images.githubusercontent.com/39028530/108022781-cc78d700-7053-11eb-8656-6f55db917187.png)

**Comment by comet5161** [comment]
```python
# install libicu67 manually.

wget https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-src.tgz

tar vzfx -C ./

cd icu/source

./configure --prefix=$PREFIX

make

export DESTDIR=/data/data/com.termux/files

make install

```

**Comment by its-pointless** [comment]
i updated mongodb

**Comment by velumanik** [comment]
I am using "mongodb_4.2.9_aarch64.deb" from https://github.com/its-pointless/its-pointless.github.io/blob/master/files/24/dists/termux/extras/binary-aarch64/mongodb_4.2.9_aarch64.deb and see the error still. 

CANNOT LINK EXECUTABLE "./mongod": library "libicudata.so.67" not found

mongodb_4.2.12-1_aarch64.deb and got 
CANNOT LINK EXECUTABLE "./mongod": library "libicudata.so.69" not found
