### ISSUE TITLE
Installing octave doesn't install required libatlas package

### ISSUE THREAD

**Issue by lgasp** [its-pointless/gcc_termux#12]
I added its-pointless repository to sources.list, then installed octave package. 
Launching octave caused an error where "libtatlas.so" could not be found.
Installing "libatlas" package solved the issue.

I would suggest to add libatlas as a dependency of octave package, if possible.

Anyway, thank you for the good work

Livio

**Comment by its-pointless** [comment]
should be fixed with updates?

**Comment by lgasp** [comment]
Sorry for being  so late. I confirm it's fixed, now.
thanks
