### ISSUE TITLE
install.packages("fs") fail in android(termux)

### ISSUE THREAD

**Issue by manikaran1993** [its-pointless/gcc_termux#120]
Latest R
~ $ pkg list-all r-base
Listing... Done
r-base/termux,now 4.0.3-1 aarch64 [installed]

Latest libicu

~ $ pkg list-all libicu
Listing... Done
libicu/stable,now 68.2-1 aarch64 [installed]

I am still getting error:

* installing *source* package ‘fs’ ...
** package ‘fs’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c dir.cc -o dir.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c error.cc -o error.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c file.cc -o file.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c fs.cc -o fs.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c getmode.cc -o getmode.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c id.cc -o id.o
id.cc:109:17: error: use of undeclared identifier 'getpwent';
      did you mean 'getgrent'?
  passwd* pwd = getpwent();
                ^~~~~~~~
                getgrent
/data/data/com.termux/files/usr/include/grp.h:55:22: note:
      'getgrent' declared here
static struct group* getgrent(void) { return 0; }
                     ^
id.cc:109:11: error: cannot initialize a variable of type
      'passwd *' with an rvalue of type 'struct group *'
  passwd* pwd = getpwent();
          ^     ~~~~~~~~~~
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c init.cc -o init.o
id.cc:113:11: error: use of undeclared identifier 'getpwent';
      did you mean 'getgrent'?
    pwd = getpwent();
          ^~~~~~~~
          getgrent
/data/data/com.termux/files/usr/include/grp.h:55:22: note:
      'getgrent' declared here
static struct group* getgrent(void) { return 0; }
                     ^
id.cc:113:11: error: incompatible pointer types assigning to
      'passwd *' from 'struct group *'
    pwd = getpwent();
          ^~~~~~~~~~
4 errors generated.
make: *** [/data/data/com.termux/files/usr/lib/R/etc/Makeconf:177: id.o] Error 1
make: *** Waiting for unfinished jobs....
ERROR: compilation failed for package ‘fs’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/fs’

The downloaded source packages are in
        ‘/data/data/com.termux/files/usr/tmp/RtmpY154DW/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("fs") :
  installation of package ‘fs’ had non-zero exit status

**Comment by its-pointless** [comment]
Yeah i have to patch fs to get it to work. Its required for use in tidyverse. So there is a version of it in that package.

**Comment by its-pointless** [comment]
I will upload the patch i use.

**Comment by manikaran1993** [comment]
Can you please update once its done.
Thanks alot

**Comment by manikaran1993** [comment]
Hey, 
Any update on this issue?

**Comment by its-pointless** [comment]
apply these patches to fs.
https://github.com/its-pointless/gcc_termux/blob/master/R-patches/rcran-fs-Makevars.patch
https://github.com/its-pointless/gcc_termux/blob/master/R-patches/rcran-fs-id.cc.patch

**Comment by kurokirasama** [comment]
> apply these patches to fs. https://github.com/its-pointless/gcc_termux/blob/master/R-patches/rcran-fs-Makevars.patch https://github.com/its-pointless/gcc_termux/blob/master/R-patches/rcran-fs-id.cc.patch

Hi, I tried applying those patches, but I got errors:
```
git apply rcran-fs-Makevars.patch --verbose --ignore-whitespace

rcran-fs-Makevars.patch:5: trailing whitespace.
HOST := 
error: corrupt patch at line 29
```
and
```
git apply rcran-fs-id.cc.patch --verbose --ignore-whitespace

error: corrupt patch at line 11
```

Can you help please?
