### ISSUE TITLE
cannot find crt1.o crti.o crtn.o 

### ISSUE THREAD

**Issue by mjuned47** [its-pointless/gcc_termux#121]
Hello,

I have tried to build gcc-4.8.5 using ndk-r15c for android 7.

everthing compiles fine and install
But when i tried hello.c program with following command
gcc -o hello hello.c
It reports error 
Cannot find crt1.o
Cannot find crtn.o
Cannot find crri.o

Is there anything that i missed during configuration ?
Or any patch ?

**Comment by its-pointless** [comment]
That has nothing to do with what i am doing. But anyway what is  likely occurring is the binutils not being correct in someway. Its using the host binutils not the target or something like that.

**Comment by mjuned47** [comment]
Ok i fixed it ,
Now the problem when i compile a library :
 
#error "libc++ does not support using GCC with C++03. Please enable C++11"

Also when i type "gcc-v"
I don't see message like "Supported LTO compression algorithms: zlib zstd" which i see in your gcc build

Is there anything that i'm missing?
