### ISSUE TITLE
Cmake failed any solution please...

### ISSUE THREAD

**Issue by Saikatsaha1996** [its-pointless/gcc_termux#125]
Please waiting for solution
![Screenshot_2021-07-08-00-48-22-008_com termux](https://user-images.githubusercontent.com/72664192/124816492-356ed600-df86-11eb-9fa2-6a1e263ba77c.jpg)

**Comment by strikersix23** [comment]
Same here

**Comment by strikersix23** [comment]
Cmake is missing files for gcc
