### ISSUE TITLE
Linking extra functions from the gnu c standard

### ISSUE THREAD

**Issue by moshiur-raj** [its-pointless/gcc_termux#127]
gcc fails to link the extra functions provided by gnu c standard. I guess I need to install the gnu c library for that but I cannot find anything like that in your repo.
I need a thread safe random number generator. and drand48_r() from the gnu standard seems like a good one. But I cannot compile my program in termux if I use that function.
https://www.gnu.org/software/libc/manual/html_mono/libc.html#SVID-Random

**Comment by its-pointless** [comment]
android uses the bionic libc and something like debian linux uses the gnulibc. 
if you look into the stdlib.h in termux/android you will find what is available under android/termux. Not drand48_r unfortunately.
