### ISSUE TITLE
Octave won't plot

### ISSUE THREAD

**Issue by kurokirasama** [its-pointless/gcc_termux#13]
Hello, I got this error when trying to plot:
`panic: Segmentation fault -- stopping myself...       Segmentation fault`
Regards,

**Comment by its-pointless** [comment]
Which arch you using? X86_64 i686 arm aarch64?
i don't have time to bug fix right now but i will get back to this thanks.

**Comment by kurokirasama** [comment]
Hello, thanks for looking into this whenever you can!
I'm using arm. My first question should have been, it plot supposed to work on terminal octave?
In the meantime, i created two basic plot functions using termux gnuplot package:
```
function tezplot(f)
if isa(f,'sym')
	f=pretty(f);
elseif ~isa(f,'char')
	error('error on input class')
end
c='gnuplot -e "set terminal dumb; plot ',f,' w l;"';
unix(c);
```
```
function tplot(x,y)
A=[x' y'];
save toplot.txt A -ascii;
c='gnuplot -e "set terminal dumb; plot ''toplot.txt'' w l;"';
unix(c);
```

**Comment by its-pointless** [comment]
Okay now that i have some time to check  the issue is caused by -Oz flag on arm. I due to some issues i can't update this repo for a few hours though.

**Comment by kurokirasama** [comment]
that's great!!!  looking forward to the update!! thanks!
