### ISSUE TITLE
Android version 11 :library "libicuuc.so.69" not found when run R

### ISSUE THREAD

**Issue by leechaowen** [its-pointless/gcc_termux#134]
~ $ R
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library "libicuuc.so.69" not found: needed by main executable

~ $ termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.152-perf+ #1 SMP PREEMPT Tue Aug 24 12:43:14 CST 2021 aarch64 Android
Device manufacturer:
Lenovo
Device model:
Lenovo TB-J716F

**i try to ln to other libicu .but meet another problem now:**

.../usr/lib $ ln -s libicuuc.so.70.1 libicuuc.so.69
.../usr/lib $ ln -s libicudata.so.70.1 libicudata.so.69
.../usr/lib $ ln -s libicui18n.so.70.1  libicui18n.so.69

~ $ R
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": cannot locate symbol "ucol_open_69" referenced by "/data/data/com.termux/files/usr/lib/R/lib/libR.so"...
~ $

how to fix it ? Thanks your support.

**Comment by leechaowen** [comment]
i could compiled r-base source code in termux now. i will make summary note later.

**Comment by dipayand** [comment]
Is the new version available? r-base recompiled with libcuu version 70?
