### ISSUE TITLE
Any solution for this gcc-10

### ISSUE THREAD

**Issue by Saikatsaha1996** [its-pointless/gcc_termux#143]
![Screenshot_2022-04-01-23-09-26-238_com termux](https://user-images.githubusercontent.com/72664192/161314621-0c63ee54-92e5-4654-909a-b9d01e56d417.jpg)

**Comment by martin-frbg** [comment]
Have you checked if you have any headers in /usr/include/android at all ? (Full path is probably something like /data/data/com.termux/files/usr/include/android). Possibly you need to install clang in termux first to get the NDK headers.

**Comment by Saikatsaha1996** [comment]
> Have you checked if you have any headers in /usr/include/android at all ? (Full path is probably something like /data/data/com.termux/files/usr/include/android). Possibly you need to install clang in termux first to get the NDK headers.

Already installed..

**Comment by Saikatsaha1996** [comment]
> Have you checked if you have any headers in /usr/include/android at all ? (Full path is probably something like /data/data/com.termux/files/usr/include/android). Possibly you need to install clang in termux first to get the NDK headers.

All available in $PREFIX/include..
With clang not issue.. with gcc can't find

**Comment by martin-frbg** [comment]
Strange. Seems to work for me (just tried to configure libunwind), though with the gcc-11.1 package. Does $PREFIX look correct on your system ? (Here it is   /data/data/com.termux/files/usr)

**Comment by Saikatsaha1996** [comment]
Yes $PREFIX/include i found all .h file....

How can I configure with libunwind ?

I installed gcc-10 with llvm* libllvm*

**Comment by martin-frbg** [comment]
Anything in config.log ? "configure" checks for header files by creating small C programs and trying to compile them, maybe configure is simply unable to run gcc for some other reason.

**Comment by Saikatsaha1996** [comment]
> Anything in config.log ? "configure" checks for header files by creating small C programs and trying to compile them, maybe configure is simply unable to run gcc for some other reason.

I am sorry.. I actually don't know anything about c or c++ programs.. but I faced issue everytime with configure and cmake with gcc ..

**Comment by martin-frbg** [comment]
Can you upload the config.log here ?

**Comment by Saikatsaha1996** [comment]
> Can you upload the config.log here ?

gcc can't compile ?
already patch for gcc used but same.. 

![Screenshot_2022-05-24-00-23-38-936_com termux](https://user-images.githubusercontent.com/72664192/169887829-3f6df891-d221-4b88-a702-be4b6d35789b.jpg)

**Comment by martin-frbg** [comment]
So it does find include files, but you need the workaround discussed in #141 (or copy the file I put in https://github.com/its-pointless/gcc_termux/issues/141#issuecomment-1100011783 )

**Comment by Saikatsaha1996** [comment]
> So it does find include files, but you need the workaround discussed in #141 (or copy the file I put in [#141 (comment)](https://github.com/its-pointless/gcc_termux/issues/141#issuecomment-1100011783) )

Where i can found setuppatchfor-gcc ?

![Screenshot_2022-05-24-01-00-17-342_com termux](https://user-images.githubusercontent.com/72664192/169892640-3bbaa126-cd6f-4883-8f3c-34486171b9a5.jpg)

**Comment by Saikatsaha1996** [comment]
> So it does find include files, but you need the workaround discussed in #141 (or copy the file I put in [#141 (comment)](https://github.com/its-pointless/gcc_termux/issues/141#issuecomment-1100011783) )

I added patching headers with /data/data/com.termux/files/usr/share/setup_scripts/cdefs.h-gcc-compat.diff


Is it okay?

**Comment by Saikatsaha1996** [comment]
> So it does find include files, but you need the workaround discussed in #141 (or copy the file I put in [#141 (comment)](https://github.com/its-pointless/gcc_termux/issues/141#issuecomment-1100011783) )

Same problem :(

![Screenshot_2022-05-24-01-18-49-777_com termux](https://user-images.githubusercontent.com/72664192/169895111-a173ad4c-2dbc-4d9d-9606-b0cfbd5d5e94.jpg)

**Comment by Saikatsaha1996** [comment]
I am install gcc like this way..

curl -LO https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh

pkg i gcc-9


Is it correct way ? Or i am Missing anything.. because some time gcc also cannot find any #include file

**Comment by Saikatsaha1996** [comment]
@its-pointless @martin-frbg see gcc can't find also include directory..

can you trying too compile ? If you can .. :(

https://github.com/tux-mind/libbthread

![Screenshot_2022-05-24-01-55-29-778_com termux](https://user-images.githubusercontent.com/72664192/169900427-08157e7f-f39a-4db6-aed4-aef815f65546.jpg)

**Comment by Saikatsaha1996** [comment]
Okay after adding this code gcc working.. but found one problem i know it can be solve .. 

OPENCL NOT FOUND
any solution for this ? With clang OpenCL found .. with gcc not found..

**Comment by Saikatsaha1996** [comment]
@martin-frbg  after patch all problem is solved..
Can is possible to add support for cmake ?.. gnu cmake can't compile anything ?

**Comment by strikersix23** [comment]
Cmake has an extreme hatred for gcc on termux, as well, I got partial compilation by targeting aarch64-linux-android but it failed hard, cmake is useless unless a cmake patch is included in its api-gnu.cmake files to search termuxs sysroot these are under $PREFIX/share/cmake-3.23/Modules/Platform/Android

**Comment by Saikatsaha1996** [comment]
> Cmake has an extreme hatred for gcc on termux, as well, I got partial compilation by targeting aarch64-linux-android but it failed hard, cmake is useless unless a cmake patch is included in its api-gnu.cmake files to search termuxs sysroot these are under $PREFIX/share/cmake-3.23/Modules/Platform/Android

Any solution for this ?

Gcc-10
error: conflicting types for 'gl_int_fast8_t'
![Screenshot_2022-06-03-01-44-34-173_com termux](https://user-images.githubusercontent.com/72664192/171730282-819ed9ec-ae01-49b5-a552-0ee7d2e64d91.jpg)

**Comment by Saikatsaha1996** [comment]
![Screenshot_2022-06-04-22-22-44-980_com termux](https://user-images.githubusercontent.com/72664192/172017278-7981615e-8262-4bb3-b966-3b4698a7773a.jpg)
@strikersix23 any solution please..

**Comment by strikersix23** [comment]
I don't have any solution its an issue with cmake on termux, some headers need to be patched and others need to be rewritten, this needs to be reopened and changed name to cmake header conflicts

**Comment by strikersix23** [comment]
I'm going to try something might be a few hours

**Comment by Saikatsaha1996** [comment]
> I'm going to try something might be a few hours

Okay 🤩 waiting waiting

**Comment by strikersix23** [comment]
Be aware im not a good programer and there might not be a solution

**Comment by strikersix23** [comment]
Mind telling me what you where compiling @Saikatsaha1996

**Comment by Saikatsaha1996** [comment]
> Mind telling me what you where compiling @Saikatsaha1996

https://github.com/fancyIX/sgminer-phi2-branch

Error in 

https://github.com/fancyIX/sgminer-phi2-branch/blob/master/SWIFFTX/SWIFFTX.c

**Comment by strikersix23** [comment]
Did you uncomment

//#include "stdbool.h"

**Comment by Saikatsaha1996** [comment]
> Did you uncomment
> 
> //#include "stdbool.h"

Ok trying

**Comment by Saikatsaha1996** [comment]
> Did you uncomment
> 
> //#include "stdbool.h"

No same problem..

**Comment by strikersix23** [comment]
This is crypto mining for amd gpus and therefore doesn't fit the scope of termux or termux gcc please do not ask how to build desktop hardware specific software on termux unless it can be used on mobile or is within current bounds if termux or termux gcc

**Comment by Saikatsaha1996** [comment]
> This is crypto mining for amd gpus and therefore doesn't fit the scope of termux or termux gcc please do not ask how to build desktop hardware specific software on termux unless it can be used on mobile or is within current bounds if termux or termux gcc

I already complete successfully in termux

https://github.com/Saikatsaha1996/sgminer-android.git

See this.. this is also for amd but it worked on android with termux

**Comment by Saikatsaha1996** [comment]
> This is crypto mining for amd gpus and therefore doesn't fit the scope of termux or termux gcc please do not ask how to build desktop hardware specific software on termux unless it can be used on mobile or is within current bounds if termux or termux gcc

But i can't compile it 

https://github.com/fancyIX/sgminer-phi2-branch

**Comment by strikersix23** [comment]
Its unsupported

**Comment by strikersix23** [comment]
What you are compiling is unsupported because it requires amd gpu to compile read the description

**Comment by strikersix23** [comment]
https://github.com/Saikatsaha1996/sgminer-android.git 
This is ported to android

**Comment by Saikatsaha1996** [comment]
> What you are compiling is unsupported because it requires amd gpu to compile read the description

This is also for `AMD` GPU .. but i change something
And successful compiled in android

https://github.com/Saikatsaha1996/sgminer-android.git

I just `#include <bthread.h>`
...
But i can't compile it mey for stdc99 features

**Comment by strikersix23** [comment]
Ok then why did advertise it for mali gpus
You do realize that is unethical right even I know that and the other program has protection in it to prevent it from being used like this miss matching stuff like this an saying it works without testing it 100% people can fry there

**Comment by Saikatsaha1996** [comment]
> Ok then why did advertise it for mali gpus You do realize that is unethical right even I know that and the other program has protection in it to prevent it from being used like this miss matching stuff like this an saying it works without testing it 100% people can fry there

I already tested it is working with Mali and adreno GPU
https://github.com/Saikatsaha1996/sgminer-android.git

**Comment by strikersix23** [comment]
What gpu's what devices

**Comment by Saikatsaha1996** [comment]
> What gpu's what devices

Adreno 650 GPU 
Mi 10T

**Comment by strikersix23** [comment]
here's the in the readme explain you tested under those devices and there is a risk of over heat on other devices and risk of complete lose of function under the I am not responsible warning and precede at your own risk

**Comment by strikersix23** [comment]
I cannot help you in compiling that software as it us hardcoded to x64/32 devices

**Comment by Saikatsaha1996** [comment]
> I cannot help you in compiling that software as it us hardcoded to x64/32 devices

Ohh is it SSE2 instruction ?

**Comment by strikersix23** [comment]
No

**Comment by strikersix23** [comment]
No
Its GCN cross lane instructions not supported on android

**Comment by Saikatsaha1996** [comment]
> No Its GCN cross lane instructions not supported on android

Okay oky understand.. thank you for your clarification.. actually i don't know any programing language..
Thank you for your help..

And also its-pointless gcc just working fine.. some code can't compile with termux clang.. but it's done with gcc

**Comment by Saikatsaha1996** [comment]
> > Cmake has an extreme hatred for gcc on termux, as well, I got partial compilation by targeting aarch64-linux-android but it failed hard, cmake is useless unless a cmake patch is included in its api-gnu.cmake files to search termuxs sysroot these are under $PREFIX/share/cmake-3.23/Modules/Platform/Android
> 
> Any solution for this ?
> 
> Gcc-10 error: conflicting types for 'gl_int_fast8_t' ![Screenshot_2022-06-03-01-44-34-173_com termux](https://user-images.githubusercontent.com/72664192/171730282-819ed9ec-ae01-49b5-a552-0ee7d2e64d91.jpg)

@strikersix23 but can i get this solution?

**Comment by strikersix23** [comment]
don't have a clue

**Comment by Saikatsaha1996** [comment]
> don't have a clue

Ohh actually i solved https://github.com/fancyIX/sgminer-phi2-branch/blob/master/SWIFFTX/SWIFFTX.c

But this is another error.. but i don't know why

**Comment by Saikatsaha1996** [comment]
> > > Cmake has an extreme hatred for gcc on termux, as well, I got partial compilation by targeting aarch64-linux-android but it failed hard, cmake is useless unless a cmake patch is included in its api-gnu.cmake files to search termuxs sysroot these are under $PREFIX/share/cmake-3.23/Modules/Platform/Android
> > 
> > 
> > Any solution for this ?
> > Gcc-10 error: conflicting types for 'gl_int_fast8_t' ![Screenshot_2022-06-03-01-44-34-173_com termux](https://user-images.githubusercontent.com/72664192/171730282-819ed9ec-ae01-49b5-a552-0ee7d2e64d91.jpg)
> 
> @strikersix23 but can i get this solution?

@strikersix23  yes this problem only happened with gcc , with clang not given problem in this code

**Comment by Saikatsaha1996** [comment]
Yes this problem for gcc.. need to patch may be..

**Comment by Saikatsaha1996** [comment]
@strikersix23 😊 so ultimately i successfully build thanks for your response and support ☺️🙏

![Screenshot_2022-06-05-01-57-42-946_com termux](https://user-images.githubusercontent.com/72664192/172024598-6277cf6a-2ca2-4eb4-bef5-aef75a733c4a.jpg)
