### ISSUE TITLE
compiling R: libgomp-10 gcc-10 not found

### ISSUE THREAD

**Issue by kurokirasama** [its-pointless/gcc_termux#145]
Hello, I'm trying to install R 4.2.0 in termux. After searching around, I got to [here](https://github.com/its-pointless/gcc_termux/issues/135).
I'm trying to follow the instructions, but the libraries libgomp-10 gcc-10 are not available. 

A `pkg search` tells me that are only available: libgomp-7 y 8, gcc 6-8.

I did follow all steps till here. 

EDIT:
I still tried to do it with what I had but I got this error:
```
No Fortran compiler found
```

EDIT2:
I installed `lfortran` and now I'm getting this error:
```
configure: error: cannot compile a simple Fortran program
```
in the log, this is the error:
```
configure:8499: gfortran -c -g  conftest.f >&5
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/gcc/aarch64-linux-android/8.3.0/f951": library "libz.so.1" not found: needed by main executable
```
I checked and `zlib` is installed and `libz.so.1` is in `$PREFIX/lib`

**Comment by kurokirasama** [comment]
`export LD_LIBRARY_PATH=$PREFIX/lib` fixed it.

**Comment by leechaowen** [comment]
i meet such issue before. need install gcc-8 not gcc-10. run below command.

```
pkg install   libgomp-8 gcc-8 libgfortran5

termux-setupgcc-8

termux-setupclang-gfort-8
```

**Comment by kurokirasama** [comment]
yeah, I forgot to mention that when I closed the issue...
