### ISSUE TITLE
Can't run Octave: libarpack error

### ISSUE THREAD

**Issue by kurokirasama** [its-pointless/gcc_termux#16]
Hello,
I have to do a fresh install of termux. I installed Octave and Octave-dev and when running Octave I got this error
```
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "sqrtf" referenced by "libarpack.so"... 
```
Any ideas?

**Comment by its-pointless** [comment]
For some reason its not linked against libm.so.
Dunno how that happened
Fix it now

**Comment by kurokirasama** [comment]
I did a fresh install of termux again, in case a miss something. Doing exactly the same now I have to got this error:
```
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "ztrsen_" referenced by "liboctinterp.so"...
```

**Comment by its-pointless** [comment]
are you using android 5?

anyway don't reinstall termux
install patchelf
patchelf --add-needed libopenblas.so ~/../usr/bin/octave-cli

**Comment by kurokirasama** [comment]
Yes, Android 5.1.1.
I did what you suggested but I'm still getting the error:
```
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "ztrsen_" referenced by "liboctinterp.so"...
```

**Comment by kurokirasama** [comment]
I just upgraded and everything seems fine. Thank you very much!

**Comment by its-pointless** [comment]
should install now properly after the update?

**Comment by kurokirasama** [comment]
hello, the only issue is that i can't install package  parallel, i got
```
configure: error: required system functions not found
```
then a lot of checking and finally:
```pkg: error running the configure script for parallel
error: called from
    configure_make at line 78 folumn 9
    install at line 192 column 7
    pkg at line 394 column 9
```

**Comment by its-pointless** [comment]
Yeah for some reason the configure script isn't detecting modf.

**Comment by its-pointless** [comment]
LDFLAGS="-lm"  needs to be set. Either in shell before launching octave or setenv LDFLAGS -lm

**Comment by kurokirasama** [comment]
Thanks! It worked. This is only for installing the package, or should I add the command to octaverc file?

**Comment by its-pointless** [comment]
Add it to file. linking the math lib is a fair assumption in octave.

**Comment by kurokirasama** [comment]
ok. thanks!
