### ISSUE TITLE
How can I add this repo???

### ISSUE THREAD

**Issue by GreenJoey** [its-pointless/gcc_termux#2]
I just saw your repos and I would loke to add it in my Termux repos but can you tdll me the exact url??? And I can't can you tell me which .debs are needed for a full gcc installation???

**Comment by its-pointless** [comment]
yeah its kind of disorganized 
gcc-6_6.3.0_arm.deb 
this is gcc-6 version 6.3.0 arm. You need this and libgfortran in the required arms libs and if you want gcov
gcov-6_6.3.0_arm.deb . 
substitute aarch64 for aarch64 . 
if you want url for each file using web site ... click on em and downoad
i guess  https://github.com/its-pointless/gcc_termux/blob/master/gcc-6_6.3.0_aarch64.deb?raw=true will work? i dunno
