### ISSUE TITLE
R build missing cairo

### ISSUE THREAD

**Issue by arietal** [its-pointless/gcc_termux#20]
Hello

I have tried your R build and it looks great. However, it seems it was built with cairo disabled.
I was trying for 3 days to build it myself and hit a snag with MBCS support. Seems the termux iconv is not suitable for building R. Anyway to make a long story short, would it be possible for you to build R with cairo support?
Thanks. Having attempted this myself, I know this was no walk in the park.

Arie

**Comment by its-pointless** [comment]
If i remember correctly cairo needs cairo-pango and tcl and they all need X to work. I have gotten them to work before because someone else had gotten x working (via vnc or xsdl on googleplay) previously.

**Comment by arietal** [comment]
There are a couple of hacks you need to pull, but you can build cairo without X.
You can pass the --without-x parameter to configure. It will attempt to test for cairo, but will fail anyway because it is going to be looking for xlib.h (even though it does not use it in the test). You can simply modify the configure script to generate the test case without that include, and it seems to work fine. R that builds can do cairo_pdf() for example. The problem I hit was elsewhere (with iconv, which you seem to have solved already).

**Comment by its-pointless** [comment]
To build a working libiconv for R you need to include android-support-dev langinfo.h when you compile it. When you compile R you can't use the iconv.h from libandroid-support-dev at all but yiu still need langinfo.h. so you should link -landroid-support first then proper libiconv library.  Also --disable-nls when configuring R.

**Comment by its-pointless** [comment]
Cairo added
