### ISSUE TITLE
Cannot build anything with gfortran-7

### ISSUE THREAD

**Issue by ashindin** [its-pointless/gcc_termux#24]
Cannot build anything with gfortran-7 and libgfortran4 (or libgfortran):
`/data/data/com.termux/files/usr/bin/ld: cannot find -lgfortran`

**Comment by its-pointless** [comment]
is the libgfortran symlink missing? 
oh yeah i will fix it 
in the mean time just ln -s libgfortran.so.4 libgfortran.so
