### ISSUE TITLE
cargo fails with missing dependency

### ISSUE THREAD

**Issue by unode** [its-pointless/gcc_termux#26]
On Android 5.0, i686, cargo fails with:
```
CANNOT LINK EXECUTABLE: could not load library "libgit2.so" needed by "cargo"; caused by library "libgit2.so" not found
```
Immediately after `pkg install cargo`. This seems to hint at a missing runtime dependency.

However, manually running `pkg install libgit2` and re-running `cargo` results in a segfault and no additional output.

**Comment by its-pointless** [comment]
Hmm i screwed that one up might have to downgrade.

**Comment by its-pointless** [comment]
yeah cargo 0.23 for i686 was broken which is why i took it down last working was 1.22.0
https://github.com/its-pointless/its-pointless.github.io/raw/master/files/dists/termux/extras/binary-i686/cargo_0.22.0_i686.deb

**Comment by its-pointless** [comment]
Good news and bad news. Bad news is that i can't cross compile cargo for i686 for some reason. jemalloc issues shouldn't be using jemalloc??. Good news is that I can can compile a working version on device. so i will get a working package in a few hours if i get some time.

**Comment by its-pointless** [comment]
Done ...

**Comment by unode** [comment]
That was a quick one. Thanks!
Confirmed on my device.
