### ISSUE TITLE
nim failed while compiling program

### ISSUE THREAD

**Issue by yunfan** [its-pointless/gcc_termux#27]
hi the irc guys tell me to report this bug here

i am using your repo in my termux and installed nim

but it dont works when compiling

this is a screenshot showing the errors
![1636395409](https://user-images.githubusercontent.com/438913/35136651-b9687062-fd1f-11e7-9186-bff21957b0cb.jpg)

also i had use ltrace to trace the compiling, here is a detail logs
[c.zip](https://github.com/its-pointless/gcc_termux/files/1645508/c.zip)

**Comment by its-pointless** [comment]
can only reproduce on aarch64. 
??
i will investigate the matter

**Comment by its-pointless** [comment]
ok it is possible to build on device using the linux path as opposed to the android path but it requires sigtimedwait symbol on libc.so. so it doesn't actually compile from cross compiler like that though.

**Comment by its-pointless** [comment]
ok fixed uploaded
