### ISSUE TITLE
Package Request: Updated rust stable release

### ISSUE THREAD

**Issue by Church-** [its-pointless/gcc_termux#31]
Just wanted to get the latest release of rust stable and cargo, since it has a few new changes including a nice style formatter like gofmt built in. Or well it can be added using rustup component add rustfmt-preview at least. Would definitely love that added

**Comment by its-pointless** [comment]
There is a bug in current release rust that means i would have to do a lot of work to get it compile. Good news is that a 1.24.1 is due soon which should fix said bug.

**Comment by its-pointless** [comment]
done

**Comment by hcpl** [comment]
`rustc` is broken now for me: it silently exits with code 1 regardless of parameters.

`cargo` works fine, but stucks whenever `rustc` is involved:
```
$ cargo build
error: process didn't exit successfully: `rustc -vV` (exit code: 1)
```

**Comment by hcpl** [comment]
Pinging @its-pointless in case if you didn't notice my message

**Comment by its-pointless** [comment]
which arch are you using?

**Comment by its-pointless** [comment]
i literally just tried all archs and each would compile with cargo engaging rustc. 
What version of android are you using and what are you compiling?

**Comment by hcpl** [comment]
OS info: Android 7.0 and
```
$ uname -srm
Linux 3.18.31-perf-g5d1394b8 aarch64
```

I tried to compile anything at all and `rustc` would still not work. To reproduce the simplest case,
```
$ echo 'fn main() {}' > foo.rs
$ rustc foo
$ echo $?
1
$ ls
foo.rs
```

**Comment by its-pointless** [comment]
it returns 0 here...
this is odd.

**Comment by its-pointless** [comment]
remake a new issue
