### ISSUE TITLE
can't open octave

### ISSUE THREAD

**Issue by kurokirasama** [its-pointless/gcc_termux#32]
Hello,

I recently changed my phone. I installed termux and next octave, together with:

```
pkg install octave octave-dev python make clang gnuplot gnutls ncurses ncurses-dev libgnutls-dev units pkg-config libgfortran
pip install sympy requests slugify
```
But when running `octave-cli` i got the following error:
```
CANNOT LINK EXECUTABLE "octave-cli": cannot locate symbol "__powisf2" referenced by "/usr/lib/octave/4.2.1/liboctave.so"...
Aborted
```
Please help!
My phone, Huawei P9 Lite 2017, Android 7.0

**Comment by its-pointless** [comment]
__powisf2 is in libgfortran.so.4.0.0. looks to be an issue with linking on that specific version. Is that android 5.0 or 6 or 7 or 8?
if you want to do a quick fix install patchelf 
then do 
`patchelf --add-needed libgfortran.so.4 octave-cli`

it may not work since i have no chance to actually test this. 
To fix this properly requires a bit more effort on my part in how i deal with libgfortran etc with the version
of gcc im using.

**Comment by kurokirasama** [comment]
hi, thanks for your response. I did what you suggested, but I got
```
patchelf: getting info about 'octave-cli': No such file or directory
```

**Comment by its-pointless** [comment]
okay iv managed to reproduce... in a silly way but still
i will fix it at some point im going to do some spring cleaning of the packages.

**Comment by kurokirasama** [comment]
That's great, thanks for the help

**Comment by kurokirasama** [comment]
thanks for the update. I can open octave now, but when I'm trying to install a package I got:
```
error: urlwrite: unable to open file
error: called from
    pkg at line 384 column 23
```

**Comment by its-pointless** [comment]
are you using chroot?
if so don't use that 
...

**Comment by kurokirasama** [comment]
Do you mean if I have run `termux-chroot`? Then yes...

**Comment by kurokirasama** [comment]
hello, it seems i figured out. For some reason (probably you can answer that), termux didn't have write access to external sdcard. I give it to it and now the instalation of octave packages is succeful

**Comment by its-pointless** [comment]
good.
