### ISSUE TITLE
matplotlib broken, likely due to numpy and/or openblas

### ISSUE THREAD

**Issue by clancia** [its-pointless/gcc_termux#33]
Hi there,
after an update, I was experiencing dead ipython kernel as soon as I would try to make a plot.
Then, I tried also the following MWE
```
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(range(10))
fig.savefig('temp.png')
```
which crashes at line 4 with the message `Illegal instruction`.
Therefore, **starting _every time_ from a clean install of Termux**, I tried the following

_Scenario 1_
```
install clang python python-dev fftw libzmq libzmq-dev freetype freetype-dev libpng libpng-dev pkg-config
pip install numpy matplotlib
```
The MWE is **working**

_Scenario 2_
```
pkg  install apt curl gnupg pkg-config clang
pkg install freetype freetype-dev libpng libpng-dev libzmq-dev libzmq
curl -L https://its-pointless.github.io/setup-pointless-repo.sh | sh
pkg install python python-dev numpy scipy
pip install matplotlib
```
The MWE is **not working** and produces the `Illegal instruction` crash.

Is there a way to solve this and have numpy/scipy nicely working with matplotlib?

**Comment by its-pointless** [comment]
what version of android and what arch are you using?

**Comment by clancia** [comment]
Nougat 7.1.1

`uname -m` reports `x86_64`

Here are some more details
![screenshot_20180320-083405](https://user-images.githubusercontent.com/8330021/37641523-5ebcc81e-2c1a-11e8-86a5-cae80cccd749.png)

**Comment by its-pointless** [comment]
wait what?
kirin is not intel ...
why on earth is it using x86_64?
in termux `dpkg --print-architecture `
is x86_64?

**Comment by clancia** [comment]
No no, it is Intel!
`dpkg --print-architecture` says `x86_64`
Plus there is a solid Intel inside sticker on the tablet so no doubt about this
It is a Lenovo Yoga Book, according to the manufacturer specs it uses an Atom x5-Z8550
It must be the app I used to make the screenshot (Castro) that is completely wrong!

**Comment by its-pointless** [comment]
okay iv uploaded new numpy + scipy
on my machine it works. 
so i don't know
if all else fails try removing your compiled version of numpy?
it should work though.

**Comment by clancia** [comment]
I'll give it a try immediately, thanks!

**Comment by its-pointless** [comment]
i have to test llvm6 anyway.

**Comment by clancia** [comment]
I am still getting `Illegal instruction` and a crash

> if all else fails try removing your compiled version of numpy?

Seems reasonable, but how do I remove the compiled version of numpy while leaving scipy in place? Then I can install numpy from pip and see if it works...

**Comment by its-pointless** [comment]
i don't know at this point. Probably won't make a difference. 
i need to have think about this.

**Comment by its-pointless** [comment]
"Atom x5-Z8550"

**Comment by its-pointless** [comment]
hmmm i will come up with something tommorow.

**Comment by clancia** [comment]
> hmmm i will come up with something tommorow

well, thanks a lot in advance!

**Comment by its-pointless** [comment]
try installing https://github.com/its-pointless/gcc_termux/raw/master/openblas_0.2.20-3_x86_64.deb
using atom profile

**Comment by clancia** [comment]
Thank you very much, it works fine. The original issue with dead kernel is also solved as expected.
You really saved my day! Having my laptop being repaired for the next n weeks, this tablet is my only resource to get some work done!
Really appreciated! I am so grateful! Thank you very much!
