### ISSUE TITLE
setupgcc-7 : command not found

### ISSUE THREAD

**Issue by ronnac** [its-pointless/gcc_termux#35]
Dear,

I successfully ran setup-pointles-repo.sh on my aarch64 (LG G4).
I want to switch to the gcc with setupgcc-7, but it says command not found.

My final aim is to make theano and keras work. On my previous phone (sammsung galaxy 2) it worked.
When I install your scipy, clang and pip install theano then it says "segmentation fault" when importing theano in python. 
This seems to be compiler related.

**Comment by its-pointless** [comment]
have you install gcc-7 ?

**Comment by ronnac** [comment]
Indeed, I had not installed gcc-7. Now I have it installed and setupgcc-7 works. However, this doesn't solve my main problem: I cannot run theano with a compiler. It does work on my other phone (samsung g2, armv7, nougat) and it does work without compiler (but too slow).
Ŵhen I install clang or gcc-7, and run theano-cache, I get an error 'python.hc not found'. That goes away with the installation of python-dev, but then I get 'crypt.h not found'. I copied different files crypt.h that I found o.j. the internet to usr/include/python3.6m/ but the best result I can get is ' segmentation fault'.

Any idea? Thank you very much advance!

**Comment by its-pointless** [comment]
Install libcrypt-dev

**Comment by ronnac** [comment]
I have done so.
>>> python
Segmentation fault

Does it work on your phone?

**Comment by its-pointless** [comment]
Yes i can't reproduce.

**Comment by ronnac** [comment]
Sorry, I meant:
Python
>>> import theano
Segmentation fault

**Comment by its-pointless** [comment]
I just imported then ... no errors

**Comment by ronnac** [comment]
I want to start from a clean slate. I have the impression that uninstalling termux doesn't remove all files. How can I be sure?

**Comment by ronnac** [comment]
Apparently the problem occurs in libc.so

$ cat > tt.py
import theano
$ gdb python
(gdb) run tt.py
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x0000007fb7be5f84 in strlen ()
   from /system/lib64/libc.so
(gdb)

**Comment by vintprox** [comment]
There is no such command after setting up repository indeed. I am confused.
