### ISSUE TITLE
Rustc: "no default toolchain configured" armv7-linux-androideabi

### ISSUE THREAD

**Issue by slovak194** [its-pointless/gcc_termux#36]
Hi! After successful installation of rustc and cargo there is no possibility to use them. It looks like armv7-linux-androideabi tarbet exists, but cannot be installed for some reason. I've tried
rustup install armv7-linux-android
And
rustup install armv7-linux-androideabi
with the same result.

$ rustc
error: no default toolchain configured
$ rustup show
Default host: armv7-linux-android

no active toolchain
$

**Comment by its-pointless** [comment]
rustup doesn't work its not a fully supported os...
could you do a rustc --version?

**Comment by its-pointless** [comment]
there is a possibility its caused because my pull request for llvm-6 on termux-packages has not gone through yet...
llvm detection of what os its running on and which cpu its running on etc... is noticeably absent when it comes to android. Anyway

I literally just tried both nightly and normal rustc that i have available through apt on arm and both work.

**Comment by its-pointless** [comment]
oh yeah output of llc -version ... as well

**Comment by slovak194** [comment]
Hi! Here are requested ouputs:

rustc --version
error: no default toolchain configured

llc --version
LLVM (http://llvm.org/):
  LLVM version 6.0.0
  Optimized build.
  Default target: armv7a--linux-android
  Host CPU: cortex-a53

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
armeb      - ARM (big endian)
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    mips       - Mips
    mips64     - Mips64 [experimental]
    mips64el   - Mips64el [experimental]
    mipsel     - Mipsel
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
r600       - AMD GPUs HD2XXX-HD6XXX
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore

**Comment by its-pointless** [comment]
it looks like a very high possibility this bug of yours goes away after https://github.com/termux/termux-packages/pull/2299

**Comment by its-pointless** [comment]
Compile [this](https://github.com/its-pointless/gcc_termux/raw/21b2b4252d9f320403dca7711ae6d501ce45e74f/tripletest.cpp)
and you can see the issue.

**Comment by its-pointless** [comment]
no it works you don't have the right headers installed to compile that test.
I will compile it for you. 
Rather what is actually happening is that the cpu detection for running llvm and figuring out what kind of cpu it is and what features it uses doesn't work correctly on android. So it tends to fall back defaults. The getProcessTriple is not configured correctly. The libllvm package simply needs to be rebuilt.
If your cpu name was 32 bit exclusive it would work
You are using a cpu that is capable of running in 64bit but is using termux 32 bit arch. Setting the process triple the same as the default target will fix it ... hopefully
im not fully confident in llvm stuff as yet though

**Comment by its-pointless** [comment]
if you were using an arm proceser that don't work in 64 bit i would probably work.

**Comment by its-pointless** [comment]
ok it should work pll request went through.

**Comment by slovak194** [comment]
Hmm, but it doesn't. I've reinstalled rustc, cargo and llvm. The error is the same. Could you please tell me how to workaround this? Many thanks!

**Comment by qpehedm** [comment]
For some reason I needed to 

Manually create .cargo/bin then

cp /data/data/com.termux/files/usr/bin/rustc /data/data/com.termux/files/home/.cargo/bin/rustc

For both rustc and cargo to get it working. May be related to running official rust install procedure first?
