### ISSUE TITLE
Repository doesn't have a Release file

### ISSUE THREAD

**Issue by kongdd** [its-pointless/gcc_termux#38]
I am trying to install r-cran. But not success.
I have no idea what's wrong.

![wechat image_20180717171027](https://user-images.githubusercontent.com/9815742/42801996-d0738b8c-89e4-11e8-9316-1adba92452fb.jpg)

![wechat image_20180717171021](https://user-images.githubusercontent.com/9815742/42801986-cc14cc5e-89e4-11e8-8e93-1b3fc8c7a003.png)

**Comment by its-pointless** [comment]
Should be fixed now
