### ISSUE TITLE
no libgcc_s.so.1 installed

### ISSUE THREAD

**Issue by finnshen** [its-pointless/gcc_termux#40]
Hi, 
   After pkg install gcc-8, there is no libgcc_s.so.1. Will this be built in the future?  Thanks

**Comment by its-pointless** [comment]
Not really since it doesn't do anything that libgcc.a already does apart from cause bugs.

**Comment by finnshen** [comment]
Thanks @its-pointless .  I am trying to install tensorflow in termux which you have discuss here. After successfully installed, I found that quite a few so files are missed in termux.  https://build.nethunter.com/kalifs/kalifs-20171013 have them, I post it here in case anyone met the same issue.
