### ISSUE TITLE
cc1 and cc1plus missing from gcc packages?

### ISSUE THREAD

**Issue by jlangeveld** [its-pointless/gcc_termux#41]
Installed gcc-8 and gcc-7, but I get an error when compiling... (Same error for g++, cc1plus is missing in that case)

> gcc main.c
gcc: error trying to exec 'cc1': execvp: No such file or directory

Installation didn't mention any problem:

> apt install gcc-8
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  gcc-8
0 upgraded, 1 newly installed, 0 to remove and 0 not upg
raded.                                                  Need to get 23.1 MB of archives.                        After this operation, 89.9 MB of additional disk space will be used.
Get:1 https://its-pointless.github.io/files termux/extr$
s aarch64 gcc-8 aarch64 8.2.0-1 [23.1 MB]
Fetched 23.1 MB in 12s (1871 kB/s)
Selecting previously unselected package gcc-8.
(Reading database ... 21975 files and directories curren
tly installed.)
Preparing to unpack .../gcc-8_8.2.0-1_aarch64.deb ...
Unpacking gcc-8 (8.2.0-1) ...
Processing triggers for man (1.14.4) ...
Setting up gcc-8 (8.2.0-1) ...

**Comment by its-pointless** [comment]
dpkg -L gcc-8
Will show the location of all installed files. its working here. Whst is in the libexec directory and have you been doing something in there?

**Comment by jlangeveld** [comment]
Thanks for the hint;

The packages are OK, I managed to screw up my $PATH inside my bash setup.
Problem solved now, closing...
