### ISSUE TITLE
PGO in gcc-8

### ISSUE THREAD

**Issue by Alexei1981** [its-pointless/gcc_termux#42]
Hey.Is PGO Disabled in the GCC-8 (7.6) compiler?
I tried to profile one program with the flag -fprofile-generate and -lgcov,but the file .gcda did not appear.Why?

**Comment by its-pointless** [comment]
This is needed in your code. Otherwise it exits before writing the file.
__gcov_flush();

**Comment by its-pointless** [comment]
I suppose a better answer would be appropriate. Because of the way android linker works it doesn't pull in enough from libgcov.a to work. The android ndk itself has there libgcov src in it.
