### ISSUE TITLE
Cannot run cargo command

### ISSUE THREAD

**Issue by shelvacu** [its-pointless/gcc_termux#45]
```
$ pkg update
...
$ cargo
CANNOT LINK EXECUTABLE: library "libssl.so.1.0.0" not found
page record for 0xb6b1102c was not found (block_size=16)
```

**Comment by its-pointless** [comment]
Which arch?
And could you run ldd on cargo? 
If its unstable tool chain i know already.

**Comment by shelvacu** [comment]
Accidentally closed sorry

It is the nightly version yes.

arch: armv7l

```
$ ldd /data/data/com.termux/files/usr/opt/rust-nightly/bin/cargo
libgit2.so
libssh2.so
libcurl.so
libssl.so.1.0.0
libcrypto.so.1.0.0
libdl.so
libc.so
libm.so
```

**Comment by its-pointless** [comment]
Yes i will get around to that after ndk update which requires i upgrade 200 things so...  2  to 3 days at most. In the  mean time delete the cargo exe  and apt install cargo. Hope that works.

**Comment by its-pointless** [comment]
Should be fine now
