### ISSUE TITLE
following issue 44, has the new scipy version released with the fix?

### ISSUE THREAD

**Issue by aaronavi** [its-pointless/gcc_termux#48]
Hi

I had an issue with Scipy package issue #44 https://github.com/its-pointless/gcc_termux/issues/44#issue-360900270

has a new version of Scipy with the fix released to the repository?

thanks

**Comment by its-pointless** [comment]
Yes?
Unless i screwed up somewhere.

**Comment by aaronavi** [comment]
i am still getting the same error

**Comment by its-pointless** [comment]
Outout of
`nm -D /data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/_lib/messagestream.cpython-36m.so`
?

**Comment by aaronavi** [comment]
$ nm -D /data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/_lib/messagestream.cpython-36m.so

         U PyBaseObject_Type
         U PyBytes_FromStringAndSize
         U PyBytes_Type
         U PyCFunction_Type
         U PyCode_New
         U PyDict_DelItem
         U PyDict_GetItemString
         U PyDict_New
         U PyDict_Next
         U PyDict_SetItem
         U PyDict_SetItemString
         U PyDict_Size
         U PyErr_Clear
         U PyErr_ExceptionMatches
         U PyErr_Format
         U PyErr_GivenExceptionMatches
         U PyErr_NoMemory
         U PyErr_NormalizeException
         U PyErr_Occurred
         U PyErr_SetObject
         U PyErr_SetString
         U PyErr_WarnEx
         U PyEval_EvalCodeEx
         U PyEval_EvalFrameEx
         U PyExc_AttributeError
         U PyExc_ImportError
         U PyExc_NameError
         U PyExc_RuntimeError
         U PyExc_StopIteration
         U PyExc_SystemError
         U PyExc_TypeError
         U PyExc_ValueError
         U PyException_SetTraceback
         U PyFrame_New
         U PyFunction_Type
         U PyImport_AddModule
         U PyImport_GetModuleDict
         U PyImport_Import
         U PyImport_ImportModuleLevelObject
00001c40 T PyInit_messagestream
         U PyList_New
         U PyList_Type
         U PyMem_Malloc
         U PyMem_Realloc
         U PyMethod_Type
         U PyModule_Create2
         U PyModule_GetDict
         U PyOS_snprintf
         U PyObject_Call
         U PyObject_GenericGetAttr
         U PyObject_GetAttr
         U PyObject_GetIter
         U PyObject_Hash
         U PyObject_Not
         U PyObject_RichCompareBool
         U PyObject_SetAttr
         U PyObject_SetAttrString
         U PyThreadState_Get
         U PyTraceBack_Here
         U PyTuple_New
         U PyTuple_Pack
         U PyTuple_Type
         U PyType_Modified
         U PyType_Ready
         U PyUnicode_Decode
         U PyUnicode_DecodeLatin1
         U PyUnicode_FromFormat
         U PyUnicode_FromString
         U PyUnicode_FromStringAndSize
         U PyUnicode_FromUnicode
         U PyUnicode_InternFromString
         U Py_GetVersion
         U _PyDict_GetItem_KnownHash
         U _PyObject_GetDictPtr
		 U _PyThreadState_UncheckedGet
         U _PyType_Lookup
         U _Py_CheckRecursionLimit
         U _Py_CheckRecursiveCall
         U _Py_FalseStruct
         U _Py_NoneStruct
         U _Py_TrueStruct
000082a0 B __bss_start
         U __cxa_atexit
         U __cxa_finalize
000082a0 B __pyx_module_is_main_scipy___lib__messagestream
         U __stack_chk_fail
000082a0 D _edata
0000837c B _end
         U fclose
         U fflush
         U fopen
         U fread
         U free
         U ftell
         U malloc
         U messagestream_open_memstream
         U remove
         U rewind
$

**Comment by its-pointless** [comment]
Should be fixed?

**Comment by aaronavi** [comment]
is there a newer scipy package that i need to get, because this one still produce the error i mentioned before

**Comment by its-pointless** [comment]
Yes. scipy_1.1.0-5_i686.deb

**Comment by aaronavi** [comment]
Ok thanks, i will try it now

**Comment by aaronavi** [comment]
when i am doing apt search scipy, i am only getting 
scipy/termux,now 1.1.0-1 i686 [installed]

how do i get the newer version?

**Comment by its-pointless** [comment]
https://github.com/its-pointless/its-pointless.github.io/tree/master/files/dists/termux/extras/binary-i686

**Comment by its-pointless** [comment]
apt update
Should update?

**Comment by aaronavi** [comment]
it is working, thank you very much for all your help

BR
Aaron
