### ISSUE TITLE
octave won't open

### ISSUE THREAD

**Issue by donsfan** [its-pointless/gcc_termux#49]
When I try to run octave I get this message:
octave: no graphical display found
octave: disabling GUI features
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-4.4.1": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/octave/4.4.1/liboctinterp.so"...
Aborted (core dumped)
Tried a fresh install but got the same message.

**Comment by its-pointless** [comment]
Which arch and which version of android?

**Comment by donsfan** [comment]
I'm on Termux on a chromebook.

**Comment by its-pointless** [comment]
Okay updated packages uploaded.

**Comment by donsfan** [comment]
Thanks. It works now! Thanks for the very prompt response.
