### ISSUE TITLE
apt update error: "Error occurred while processing libsoup"

### ISSUE THREAD

**Issue by Grimler91** [its-pointless/gcc_termux#5]
Hi, thanks for providing scipy, numpy and all the other packages. I'm getting an error on "apt update" from this morning:

    apt update
    Hit:1 http://termux.net stable InRelease
    Hit:2 https://its-pointless.github.io/files termux InRelease
    Reading package lists... Error!
    E: Problem parsing dependency Depends
    E: Error occurred while processing libsoup (NewVersion2)
    E: Problem with MergeList 
    /data/data/com.termux/files/usr/var/lib/apt/lists/its-pointless.github.io_files_dists_termux_extras_binary-arm_Packages
    E: The package lists or status file could not be parsed or opened.

`apt-get clean` didn't help. Please let me know I can provide any more information.

**Comment by its-pointless** [comment]
fixed?

**Comment by Grimler91** [comment]
Yes, thanks!
