### ISSUE TITLE
gfortran missing

### ISSUE THREAD

**Issue by RalfWerner** [its-pointless/gcc_termux#52]
# Addendum to key (was only temporary - closed again)
in **p=pointless.gpg; wget https://its-pointless.github.io/$p** below I got
```--2019-04-22 16:13:40--  https://its-pointless.github.io/pointtless.gpg
Resolving its-pointless.github.io... 185.199.109.153, 185.199.111.153, 185.199.108.153, ...
Connecting to its-pointless.github.io|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

```
# below solved
Dear - hopefully _not_ pointless

What did I do wrong or can not get an answer here?

My current goal is to use **_gfortran_** on my Android Phone in Termux 1). This _**compiler**_ belongs to GCC (Gnu Compiler Collection), but is not generated by any of my actions 2).
With gcc *.c sources and make I have _**no**_ problems. For _**"pointless"**_ update, I have kept to your specifications/ instuctions. Can you help me?

1) I have reinstalled the Termux app with API from F-Droid (6/17 MB) and get with your update 2) and some packages for ssh and x11 ($x) 257 MB for the app but no $PREFIX/bin/gfortran inside.

**$ termux-info
Updatable packages:All packages up to date
System information:Linux localhost 3.18.66-gde8dc79
Termux-packages arch:aarch64
Android version:8.0.0
Device manufacturer:HUAWEI
Device model:LDN-L21**

2) I did the following pkg update

``` **pkg install termux-api x11-repo; pkg update; pkg upgrade
 x="mc openssh libxpm xterm imagemagick libx11-dev"
 pkg install coreutils make clang gnupg wget $x
 p=pointless.gpg; wget https://its-pointless.github.io/$p; apt-key add $p
 a="deb https://its-pointless.github.io/files/ termux extras"
 p=$PREFIX/etc/apt/sources.list; echo $a>>$p
 pkg install libgfortran; pkg update**
```
 and check result in $PREFIX

``` 
$ ls -l `find $PREFIX -name "*fortr*"`
**lrwxrwxrwx 1 u0_a145 u0_a145      22 Dec 20 13:27 ../usr/lib/gcc/aarch64-linux-android/6.5.0/libgfortran.so -> libgfortran.so.3.0.0
lrwxrwxrwx 1 u0_a145 u0_a145      22 Dec 20 13:27 ../usr/lib/gcc/aarch64-linux-android/6.5.0/libgfortran.so.3 -> libgfortran.so.3.0.0
-rwx------ 1 u0_a145 u0_a145 1116848 Nov  6 22:35 ../usr/lib/gcc/aarch64-linux-android/6.5.0/libgfortran.so.3.0.0
lrwxrwxrwx 1 u0_a145 u0_a145      86 Dec 20 13:27 ../usr/lib/libgfortran.so.3 -> /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/6.5.0/libgfortran.so.3
lrwxrwxrwx 1 u0_a145 u0_a145      90 Dec 20 13:27 ../usr/lib/libgfortran.so.3.0.0 -> /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/6.5.0/libgfortran.so.3.0.0
-rw------- 1 u0_a145 u0_a145    8607 Jun  4  2018 ../usr/share/mc/syntax/fortran.syntax
-rw-r--r-- 1 u0_a145 u0_a145     675 Dec 20 13:27 ../usr/var/lib/dpkg/info/libgfortran.list
-rw-r--r-- 1 u0_a145 u0_a145     122 Dec 20 13:27 ../usr/var/lib/dpkg/info/libgfortran.md5sums**
```

**Comment by its-pointless** [comment]
2 commands

pkg install gcc-8
setupclang-gfort-8

**Comment by RalfWerner** [comment]
In between I've extent the **_pkg install_** by **_libgfortran5_** (gcc-8 refer to this) but without effect.

**Comment by its-pointless** [comment]
looks like its not linked properly
gfortran file.f 
Compiles fine. To get object file linked correctly just using gfortran command as linker should work. But needs to be linked against libm.so for math and libgfortran.so.5   for _gfortran_st_open

**Comment by its-pointless** [comment]
You probably need to recompile and link it again. Unless libgfortran.so.5 is missing  _gfortran_st_open. You can test by the command
nm -D libgfortran.so.5 | grep _gfortran_st_open

**Comment by RalfWerner** [comment]
Thank you very much!
With your last tip (gfrortran instead of gcc for ld) I could translate my 160 tloc in 5 minutes and run the **exe** *). So we can close this issue - You or I?
You a blessed Christmas
Ralf
*) **exe** (cuteables) use **_x11_** for GUI description. github refer to https://github.com/termux/x11-packages and this to https://github.com/xeffyr and XServer XSDL, whose development has unfortunately been discontinued. Do you have any experience with it or can you give me a hint where I can get support?

**Comment by RalfWerner** [comment]
I close this issue, Presumably you have nothing to do with X11. If so, I would have some questions about that, the other Termux members have not given me an answer yet

**Comment by AI-Pranto** [comment]
I can't install gcc in my Android OS. So far, I followed 
`curl -LO https://its-pointless.github.io/setup-pointless-repo.sh` and 
`bash setup-pointless-repo.sh` commands. 
But `pkg install libgfortran` shows the `E: Unable to locate package libgfortran` error. 
How can I install it?

**Comment by its-pointless** [comment]
> I can't install gcc in my Android OS. So far, I followed
> `curl -LO https://its-pointless.github.io/setup-pointless-repo.sh` and
> `bash setup-pointless-repo.sh` commands.
> But `pkg install libgfortran` shows the `E: Unable to locate package libgfortran` error.
> How can I install it?

pkg install gcc-9

**Comment by AI-Pranto** [comment]
Thanks @its-pointless

**Comment by AI-Pranto** [comment]
Still now gfortran missing. Should I use `setupclang-gfort-9`? But If I do, It shows 

```
rm: cannot remove 'gcc': No such file or directory

```

**Comment by AI-Pranto** [comment]
Ooops, Unfortunately, I forgot to install clang. 
One more question, I have installed openssl already, but got `FATAL ERROR: can not find openssl!`
Why It shows this kind of error? @its-pointless

**Comment by AI-Pranto** [comment]
I have solved the problem. Thanks @its-pointless

**Comment by AI-Pranto** [comment]
I think this issue suited best here. I try to install OpenMPI from source but `./configure FC=gfortran` shows the following error 

```
*** Fortran compiler
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking whether ln -s works... yes
checking if Fortran compiler works... no
**********************************************************************
* It appears that your Fortran compiler is unable to produce working
* executables.  A simple test application failed to properly
* execute.  Note that this is likely not a problem with Open MPI,
* but a problem with the local compiler installation.  More
* information (including exactly what command was given to the
* compiler and what error resulted when the command was executed) is
* available in the config.log file in the Open MPI build directory.
**********************************************************************
configure: error: Could not run a simple Fortran program.  Aborting.
```
```
gfortran --version
GNU Fortran (GCC)  9.3.0
```
How to fix this problem?
