### ISSUE TITLE
CANNOT LINK EXECUTABLE: cannot locate symbol "nl_langinfo" referenced by "newsboat"...

### ISSUE THREAD

**Issue by Quasic** [its-pointless/gcc_termux#55]
I think newsboat-android-5.0 needs a TERMUX_PKG_REVISION bump after that nl_langinfo thing?

**Comment by WeeBeasties** [comment]
pretty sure that r-base depends upon the same thing.

**Comment by its-pointless** [comment]
Yes im about to do a big update to termux using new ndk. Which means new libc++ which means i will have to upload everything again anyway. I only want to do that once.... 
In the meantime i will figure something out if nothing moves on this front.

**Comment by its-pointless** [comment]
Okay new newsboat and i updated libgnuiconv so r-base should work now.
