### ISSUE TITLE
gnatmake: link failed

### ISSUE THREAD

**Issue by calheiros** [its-pointless/gcc_termux#56]
`$ gnat make main.adb`

**OUTPUT**:

gnatbind -x main.ali
gnatlink main.ali
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(libunwind.o): in function `_Unwind_RaiseException':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/libunwind.S:356: multiple definition of `_Unwind_RaiseException'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:667: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(libunwind.o): in function `_Unwind_Resume':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/libunwind.S:357: multiple definition of `_Unwind_Resume'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:705: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(libunwind.o): in function `_Unwind_Resume_or_Rethrow':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/libunwind.S:358: multiple definition of `_Unwind_Resume_or_Rethrow'; /data/data/com.termux/files/usr/lib/libunwind.a(UnwindLevel1-gcc-ext.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/UnwindLevel1-gcc-ext.c:44: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(libunwind.o): in function `_Unwind_Backtrace':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/libunwind.S:360: multiple definition of `_Unwind_Backtrace'; /data/data/com.termux/files/usr/lib/libunwind.a(UnwindLevel1-gcc-ext.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/UnwindLevel1-gcc-ext.c:105: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `__aeabi_unwind_cpp_pr0':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/unwind-arm.c:494: multiple definition of `__aeabi_unwind_cpp_pr0'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:421: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `_Unwind_GetCFA':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:401: multiple definition of `_Unwind_GetCFA'; /data/data/com.termux/files/usr/lib/libunwind.a(UnwindLevel1-gcc-ext.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/UnwindLevel1-gcc-ext.c:205: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `_Unwind_Complete':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:528: multiple definition of `_Unwind_Complete'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:691: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `_Unwind_DeleteException':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:537: multiple definition of `_Unwind_DeleteException'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:976: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `_Unwind_VRS_Get':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/unwind-arm.c:163: multiple definition of `_Unwind_VRS_Get'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:868: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `_Unwind_VRS_Set':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/unwind-arm.c:193: multiple definition of `_Unwind_VRS_Set'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:756: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(unwind-arm.o): in function `_Unwind_VRS_Pop':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/unwind-arm.c:220: multiple definition of `_Unwind_VRS_Pop'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:883: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(pr-support.o): in function `__gnu_unwind_frame':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/pr-support.c:318: multiple definition of `__gnu_unwind_frame'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:983: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(pr-support.o): in function `_Unwind_GetRegionStart':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/pr-support.c:346: multiple definition of `_Unwind_GetRegionStart'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:958: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(pr-support.o): in function `_Unwind_GetLanguageSpecificData':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/pr-support.c:357: multiple definition of `_Unwind_GetLanguageSpecificData'; /data/data/com.termux/files/usr/lib/libunwind.a(Unwind-EHABI.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/Unwind-EHABI.cpp:723: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(pr-support.o): in function `_Unwind_GetDataRelBase':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/pr-support.c:377: multiple definition of `_Unwind_GetDataRelBase'; /data/data/com.termux/files/usr/lib/libunwind.a(UnwindLevel1-gcc-ext.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/UnwindLevel1-gcc-ext.c:67: first defined here
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/lib/libgcc_real.a(pr-support.o): in function `_Unwind_GetTextRelBase':
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/pr-support.c:383: multiple definition of `_Unwind_GetTextRelBase'; /data/data/com.termux/files/usr/lib/libunwind.a(UnwindLevel1-gcc-ext.o):/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libunwind_llvm/src/UnwindLevel1-gcc-ext.c:77: first defined here
collect2: error: ld returned 1 exit status
gnatlink: error when calling /data/data/com.termux/files/usr/bin/gcc
gnatmake: *** link failed.

**Comment by its-pointless** [comment]
Looks to be needing to link with libgcc.a in lib/gcc/arm-linux-androideabi/libgcc.a but is linking with $PREFIX/lib/libgcc.a instead which is a script for clang. If its calling gcc execute command setupgcc-8 then try again to make sure its not trying to using clang. 
Use command setupclang to switch back.

**Comment by calheiros** [comment]
`$ gnat make main.adb `
 gcc -c main.adb
clang-7: error: unknown argument: '-gnatea'
clang-7: error: unknown argument: '-gnatez'
gnatmake: "main.adb" compilation error

**Comment by its-pointless** [comment]
Use fhe command 
`setupgcc-8`
Its a script that sets up gcc and g++ as in gnu gcc.
Switch back to using clang using the command 
`setupclang` 
So gcc will link to llvm clang

**Comment by its-pointless** [comment]
gcc-8 -c main.adb

**Comment by calheiros** [comment]
I have run these commands several times before opening the ticket, but I result is the same.

**Comment by calheiros** [comment]
`$ gcc-8 -c main.adb`
`$ gnatbind main.ali`
`$ gnatlink main`
clang-7: error: unknown argument: '-mtls-dialect=gnu'
clang-7: error: unknown argument: '-mbionic'
clang-7: error: unknown argument: '-gnatA'  clang-7: error: unknown argument: '-gnatWb'
clang-7: error: unknown argument: '-gnatiw'
clang-7: error: unknown argument: '-gnatws'

**Comment by its-pointless** [comment]
It shouldn;t be calling clang at all.

**Comment by its-pointless** [comment]
mv $PREFIX/libgcc.a $PREFIX/libgcc.a.script 

Now try again.
On arm after doing that
 ➜  ~ gcc-8 -c hello.adb                                                                                                                                                                ➜  ~ gnatbind hello.ali                                                                                                                                                                ➜  ~ gnatlink hello                                                                                                                                                                    ➜  ~ ./hello
Hello, World!

**Comment by its-pointless** [comment]
Looks to he an arm only issue. I will fix it properly tommorow.

**Comment by calheiros** [comment]
Thanks a lot, it's working now. :)

**Comment by calheiros** [comment]
Only the path $PREFIX/libgcc.a is wrong, forgot the Sub directory lib: $PREFIX/lib/libgcc.a
