### ISSUE TITLE
fp-compiler: Can't find unit system used by program

### ISSUE THREAD

**Issue by calheiros** [its-pointless/gcc_termux#57]
`$ fpc main.pas`
`Fatal: Can't find unit system used by main`
`Fatal: Compilation aborted`                 
 `Error: /data/data/com.termux/files/usr/bin/ppcarm returned an error exitcode`

main.pas file content:

```pascal
program main;

begin
   writeln('Olá mundo!');
end.
```
`ppcarm` always returns an error for any script.

**Comment by its-pointless** [comment]
should be good now.

**Comment by calheiros** [comment]
Yes, it's working fine. Thank you very much.
