### ISSUE TITLE
Cannot install R packages in Termux Android

### ISSUE THREAD

**Issue by trongquy** [its-pointless/gcc_termux#58]
Hi all,
I wrote a R function and it runs perfectly on desktop. Recently, I would be interested to use that function in my Android phone (sony xperia) because i am away sometimes. I did follow instruction from below post to install Termux, R and tidyverse successfully
https://www.reddit.com/r/rstats/comments/8rnxz2/instructions_for_r_onthego/
To activate my function, i need to install some more packages incl openxlsx, tidyr, dplyr, scales. I did install them all by install.packages() but when I load the function with source() and run it in R environment, an error comes out that states the package is not found or installed. Any help and suggestion would be much appreciated
Thank you
Martin

**Comment by its-pointless** [comment]
install tidy verse via apt if it's still not working. apt install r-cran-tidyverse

**Comment by trongquy** [comment]
Thank you for your help. I did follow another turtorial and the problem is fixed
