### ISSUE TITLE
r-base libicu63 dependency issue

### ISSUE THREAD

**Issue by hiuser123** [its-pointless/gcc_termux#59]
R returns an error when trying to run:
`R
WARNING: linker: /data/data/com.termux/files/usr/lib/R/bin/exec/R: unused DT entry: type 0x6ffffef5 arg 0x2a8
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libicuuc.so.63" not found`

I have libicu installed, but the current version iws libicuuc.so.64

is there a workaround for this?

**Comment by calheiros** [comment]
I'm getting the same error:
`$ R    `                                    
 `CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library`
`"libicuuc.so.63" not found `               
  
`[1]+  Stopped`

**Comment by its-pointless** [comment]
should be fixed
