### ISSUE TITLE
compile error gcc-8

### ISSUE THREAD

**Issue by dekubi** [its-pointless/gcc_termux#60]

**Comment by dekubi** [comment]
^~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/string.h:269:51: error: attributes are not allowed on a function-definition
 const char* strpbrk(const char* h, const char* n) __prefer_this_overloa {
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from /data/data/com.termux/files/usr/include/c++/v1/string.h:61,
                 from /data/data/com.termux/files/usr/include/stdio.h:47,
                 from /data/data/com.termux/files/usr/include/c++/v1/stdio.h:108,
                 from /data/data/com.termux/files/usr/include/wchar.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/wchar.h:119,
                 from /data/data/com.termux/files/usr/include/c++/v1/iosfwd:90,
                 from /data/data/com.termux/files/usr/include/c++/v1/ios:215,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:38,
                 from io.cpp:1:
/data/data/com.termux/files/usr/include/string.h:269:13: error: ambiguating new declaration of 'const char* strpbrk(const char*, const char*)'
 const char* strpbrk(const char* h, const char* n) __prefer_this_overload {
             ^~~~~~~
/data/data/com.termux/files/usr/include/string.h:149:7: note: old declaration 'char* strpbrk(const char*, const char*)'
 char* strpbrk(const char* __s, const char* __accept) __attribute_pure__;
       ^~~~~~~

**Comment by dekubi** [comment]
@its_pointless

**Comment by calheiros** [comment]
Try using `g++-8` instead of `gcc-8`

**Comment by dekubi** [comment]
still am receiving the same error @calheiros

**Comment by calheiros** [comment]
If possible provide your source code, please.

**Comment by dekubi** [comment]
#include <iostream>
using namespace std;

int main(){
    cout << "Hello world" << endl;
    return 0;
}

**Comment by calheiros** [comment]
Using Clang code compiled correctly as expected, but GCC failed. I Believe it is really a problem in the compiler.

Unfortunately, I can't help you.

**Comment by calheiros** [comment]
Use Clang for now

**Comment by dekubi** [comment]
Clang it shall be then. Thank you @calheiros

**Comment by its-pointless** [comment]
the issue is the header files.
the command executing the script `setup-patchforgcc` should fix this .
