### ISSUE TITLE
libiconv dependency

### ISSUE THREAD

**Issue by smaslovski** [its-pointless/gcc_termux#61]
Hi,

Just now tried adding your deb repo to termux and installing gcc-9 or -8. It fails because of a missing dependency package:
===============================================
apt-get install gcc-8
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcc-8 : Depends: libiconv but it is not installable
E: Unable to correct problems, you have held broken packages.
$ apt-get install libiconv
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libiconv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libiconv' has no installation candidate

**Comment by its-pointless** [comment]
looks like you are using the url for android 5 and 6. 
use this 
`deb https://its-pointless.github.io/files termux extras`
instead of 
`deb https://its-pointless.github.io/files/24 termux extras`

**Comment by smaslovski** [comment]
Hi,

This happens on Samsung Galaxy Tab S3 with Android 8.0. Why should I use the repo for Android 5 and 6?

**Comment by its-pointless** [comment]
because your device is currently using the repo for android 5 and 6. As such there is no libiconv package available.

**Comment by smaslovski** [comment]
Hm, indeed. That is rather unexpected. Maybe, a termux bug then?

**Comment by its-pointless** [comment]
it could be you installed termux before the newer android-7 termux repo started being used.

**Comment by smaslovski** [comment]
resolved.
