### ISSUE TITLE
cannot find -lgfortran

### ISSUE THREAD

**Issue by smaslovski** [its-pointless/gcc_termux#62]
$ setupgcc-8
$ gfortran -Wall -O3 test.f90 -o test
/data/data/com.termux/files/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status

**Comment by smaslovski** [comment]
$ setupgcc-8
gcc now points to gcc-8
$ gcc -Wall -O3 saw.f90 -o saw
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cck8es4Y.o: in function `__diffraction_MOD_u0':
saw.f90:(.text+0x3a4): undefined reference to `cexp'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cck8es4Y.o: in function `__diffraction_MOD_g':
saw.f90:(.text+0x460): undefined reference to `cexp'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cck8es4Y.o: in function `MAIN__':
saw.f90:(.text+0x710): undefined reference to `_gfortran_st_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x720): undefined reference to `_gfortran_transfer_character_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x728): undefined reference to `_gfortran_st_write_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x74c): undefined reference to `_gfortran_st_read'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x75c): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x76c): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x77c): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x78c): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x794): undefined reference to `_gfortran_st_read_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xafc): undefined reference to `_gfortran_transfer_complex_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xb04): undefined reference to `_gfortran_st_write_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xb48): undefined reference to `_gfortran_st_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xb58): undefined reference to `_gfortran_transfer_real_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xb68): undefined reference to `_gfortran_transfer_real_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xbc0): undefined reference to `_gfortran_spread_scalar'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xbc8): undefined reference to `_gfortran_internal_pack'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xc20): undefined reference to `_gfortran_st_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xc28): undefined reference to `_gfortran_st_write_done'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cck8es4Y.o: in function `main':
saw.f90:(.text.startup+0x8): undefined reference to `_gfortran_set_args'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text.startup+0x1c): undefined reference to `_gfortran_set_options'
collect2: error: ld returned 1 exit status

**Comment by smaslovski** [comment]
$ setupclang-gfort-8
now using clang as default compiler with gfortran-8
$ gfortran -Wall -O3 saw.f90 -o saw
/data/data/com.termux/files/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status

**Comment by smaslovski** [comment]
And, finally

$ setupclang-gfort-8
now using clang as default compiler with gfortran-8
$ gcc -Wall -O3 saw.f90 -o saw
$ ls saw
ls: cannot access 'saw': No such file or directory

Runs silently, but no executable file produced.

**Comment by its-pointless** [comment]
Due to compatibility issues clang doesn't compile fortran like that on android. have to use gfortran instead of gcc.
It could also be mixing android api 24 (android 7 and up) with android  api 21 (android 5 and up) packages.

**Comment by its-pointless** [comment]
Or setupgcc-8 then try again.

**Comment by its-pointless** [comment]
lets go back to the beginning
data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cck8es4Y.o: in function __diffraction_MOD_u0': saw.f90:(.text+0x3a4): undefined reference to cexp'
cexp is in libm.so... odd

**Comment by smaslovski** [comment]
Next try: I deleted and reinstalled Termux from scratch. Now I am sure it is uses -24 repository. I added your repo with the help of your script and then installed gcc-9. This is what I get now:

$ ls -l `which gcc`
lrwxrwxrwx 1 u0_a215 u0_a215 5 May 19 02:07 /data/data/com.termux/files/usr/bin/gcc -> gcc-9
$ gfortran -Wall -O3 saw.f90 -o saw
/data/data/com.termux/files/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
$ gcc -Wall -O3 saw.f90 -o saw
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cc9DWIWL.o: in function `__diffraction_MOD_u0':
saw.f90:(.text+0x31c): undefined reference to `cexp'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cc9DWIWL.o: in function `__diffraction_MOD_g':
saw.f90:(.text+0x600): undefined reference to `cexp'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cc9DWIWL.o: in function `MAIN__':
saw.f90:(.text+0x88c): undefined reference to `_gfortran_st_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8a0): undefined reference to `_gfortran_transfer_character_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8a8): undefined reference to `_gfortran_st_write_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8cc): undefined reference to `_gfortran_st_read'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8dc): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8ec): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8fc): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x90c): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x914): undefined reference to `_gfortran_st_read_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xc64): undefined reference to `_gfortran_transfer_complex_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xc6c): undefined reference to n_st_write_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8cc): undefined reference to `_gfortran_st_read'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8dc): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8ec): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x8fc): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x90c): undefined reference to `_gfortran_transfer_real'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0x914): undefined reference to `_gfortran_st_read_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xc64): undefined reference to `_gfortran_transfer_complex_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xc6c): undefined reference to `_gfortran_st_write_done'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xcb8): undefined reference to `_gfortran_st_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xcc8): undefined reference to `_gfortran_transfer_real_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xcd8): undefined reference to `_gfortran_transfer_real_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xd2c): undefined reference to `_gfortran_spread_scalar'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xd34): undefined reference to `_gfortran_internal_pack'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xd94): undefined reference to `_gfortran_st_write'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text+0xd9c): undefined reference to `_gfortran_st_write_done'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/cc9DWIWL.o: in function `main':
saw.f90:(.text.startup+0x8): undefined reference to `_gfortran_set_args'
/data/data/com.termux/files/usr/bin/ld: saw.f90:(.text.startup+0x1c): undefined reference to `_gfortran_set_options'
collect2: error: ld returned 1 exit status

**Comment by its-pointless** [comment]
`nm -A -D $PREFIX/lib/libgfortran.so | grep _gfortran_st_read`                                                                                                                   /data/data/com.termux/files/usr/lib/libgfortran.so:00000000000cea28 T _gfortran_st_read                                                                                                /data/data/com.termux/files/usr/lib/libgfortran.so:00000000000ced88 T _gfortran_st_read_done

**Comment by smaslovski** [comment]
$
$ nm -A -D $PREFIX/lib/libgfortran.so | grep _gfortran_st_read
nm: '/data/data/com.termux/files/usr/lib/libgfortran.so': No such file
$ dpkg -L gcc-9 | grep libgfortran.so
$

**Comment by its-pointless** [comment]
Install libgfortran5

**Comment by its-pointless** [comment]
My mistake i screwed up dependencies.

**Comment by smaslovski** [comment]
you should add it as a dependency to your gcc-X package.

**Comment by its-pointless** [comment]
Yep i apoligise my fault. 
Sorry about that.
