### ISSUE TITLE
broken symlinks in setup-scripts

### ISSUE THREAD

**Issue by smaslovski** [its-pointless/gcc_termux#63]
There are two broken symlinks associated with setup-scripts package:

$ find -L ../usr/bin -type l
../usr/bin/termux-setupgcc-6
../usr/bin/termux-setupclang-gfort-6
$ ../usr/bin/termux-setupgcc-6
bash: ../usr/bin/termux-setupgcc-6: No such file or directory
$ ../usr/bin/termux-setupclang-gfort-6
bash: ../usr/bin/termux-setupclang-gfort-6: No such file or directory

**Comment by its-pointless** [comment]
Yeah iv already got that fixed. Just havent bothered to upload it yet because im a lazy bugger.

**Comment by smaslovski** [comment]
Please do :)
