### ISSUE TITLE
Gcc break after update libiconv

### ISSUE THREAD

**Issue by rendiix** [its-pointless/gcc_termux#64]
![Screenshot_2019-05-21-12-10-55-882_com termux](https://user-images.githubusercontent.com/16639978/58070143-279d4180-7bc2-11e9-8c6d-8a3ddd8f899d.png)

**Comment by its-pointless** [comment]
You have to change my repo url so you get the api 24 binaries.

**Comment by its-pointless** [comment]
No wait its my stuff that needs updating on android-5 dist ...
