### ISSUE TITLE
packages ‘utils’  and 'stats' not found in R

### ISSUE THREAD

**Issue by cityofsmiles87** [its-pointless/gcc_termux#66]
Hi. I've been using R for a year but after updating termux, I think something broke. I don't know what to do so I just uninstalled it. Any help is welcome. 
My device is Asus Zenfone 3 running Android Nougat. Here's the output when I run R. 

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-android (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error: package or namespace load failed for ‘utils’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
Error: package or namespace load failed for ‘stats’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found
2: package ‘stats’ in options("defaultPackages") was not found

**Comment by its-pointless** [comment]
Same as https://github.com/its-pointless/its-pointless.github.io/issues/29 
I can't reproduce the error myself. So i don't know.

**Comment by its-pointless** [comment]
maybe strace output logcat etc but i don't know.

**Comment by its-pointless** [comment]
i have an idea will upload new version of R

**Comment by cityofsmiles87** [comment]
Thank you. I hope that fixes it.

**Comment by cityofsmiles87** [comment]
I just updated R to version 3.6.1 but the problem still remains. I'll try the solution suggested in its-pointless/its-pointless.github.io#29.

**Comment by cityofsmiles87** [comment]
As suggested by bobdadada, I downgraded the version of R to 3.5.3 and it's working fine now. Thanks.

**Comment by its-pointless** [comment]
only way i have been able to reproduce this error is by using the wrong repo. Using android-7 aka packages for this http://dl.bintray.com/termux/termux-packages-24 in main packages but R from  https://its-pointless.github.io/files/  
if you are using packages from http://dl.bintray.com/termux/termux-packages-24  you have to use https://its-pointless.github.io/files/24 as repo for R.

**Comment by cityofsmiles87** [comment]
Thanks, that actually fixed the problem.
