### ISSUE TITLE
no module named scipy

### ISSUE THREAD

**Issue by ogahozy** [its-pointless/gcc_termux#67]
after the installation of scipy: by pkg install scipy, the installation was succesful. but when i tried to import it, it say:
>from scipy import io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
 but import numpy worked.
i am using termux on samsung tab s5e. 
i have uninstalled and reinstalled it with out help

**Comment by its-pointless** [comment]
what is the output from termux-info?

**Comment by ogahozy** [comment]
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang
b55f2d4ebfd35bf6 on linux
                     Type "help", "copyright", "credits" or "license" for
more information.
>>> import scipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>>
