### ISSUE TITLE
RFP: Gnustep

### ISSUE THREAD

**Issue by donaldsmith2060** [its-pointless/gcc_termux#70]
I'd love to be able to use the objective c compiler and write some basic programs, maybe even gsweb

**Comment by its-pointless** [comment]
yeah this is easily do able in fact i have several different ways of doing it... 

At issue is i need to fix libffi in main packages for this to be consistently workable.

**Comment by donaldsmith2060** [comment]
I just tried the gnustep-base package on a hello world and got this:

In file included from a.m:1:                           In file included from /data/data/com.termux/files/usr/include/Foundation/NSObject.h:30:                       In file included from /data/data/com.termux/files/usr/include/Foundation/NSObjCRuntime.h:222:                 /data/data/com.termux/files/usr/include/GNUstepBase/GSObjCRuntime.h:58:11: fatal error:                             'objc/objc.h' file not found                      #include <objc/objc.h>                                          ^~~~~~~~~~~~~                                1 error generated.

I don't know who didn't provide the header hope this is constructive.

**Comment by donaldsmith2060** [comment]
Got it to link with:
gcc -I../usr/lib/gcc/i686-linux-android/8.3.0/include/ -I../usr/include/  `gnustep-config --objc-flags` -lgnustep-base -lobjc -o hello HelloWorld.m
