### ISSUE TITLE
Update rustc nightly?

### ISSUE THREAD

**Issue by kalmari246** [its-pointless/gcc_termux#74]
The current nightly is `rustc 1.37.0-nightly`.
The latest is `rustc 1.40.0-nightly`.

**Comment by its-pointless** [comment]
Issue is the size of package size doubled. Its too large for github hosting.

**Comment by kalmari246** [comment]
hot

**Comment by its-pointless** [comment]
Working on fixing this now.

**Comment by kalmari246** [comment]
did you move it to the unstable repo :eyes:

**Comment by its-pointless** [comment]
Yep

**Comment by kalmari246** [comment]
thank you a bunch!
