### ISSUE TITLE
Finding Libraries

### ISSUE THREAD

**Issue by frink** [its-pointless/gcc_termux#76]
clang finds libraries (e.g. <sys/epoll.h> or <sys/sendfile.h>) but gcc does not...

Anyone know why this is...?

**Comment by its-pointless** [comment]
which termux arch are you using ? as in 
`dpkg --print-architecture`

**Comment by frink** [comment]
arm

**Comment by frink** [comment]
I've also compiled and installed tcc and it's having the same problem...

**Comment by its-pointless** [comment]
`#include <stdio.h>`
`#include <sys/epoll.h>`
`#include <sys/sendfile.h>`
`int main() {`
`        return 0;`
`}`

this compiles fine for me using gcc. 
I can't reproduce this

**Comment by JL2210** [comment]
*header files
