### ISSUE TITLE
Can't use gcc-7 to compile c file. 

### ISSUE THREAD

**Issue by bingofancy** [its-pointless/gcc_termux#78]
$ clang he.c
$ ls
a.out  he.c  hh.c
$ gcc he.c
$ gcc
clang-9: error: no input files
$ gcc-7 he.c
In file included from /data/data/com.termux/files/usr/include/stdio.h:41:0,
                 from he.c:1:
/data/data/com.termux/files/usr/include/sys/cdefs.h:317:18: error: missing binary operator before token "("
 #if __has_builtin(__builtin_umul_overflow) || __GNUC__ >= 5

**Comment by bingofancy** [comment]
Use clang or gcc to compile is normal，but gcc-7 is error

**Comment by its-pointless** [comment]
Use command setup-patchforgcc

**Comment by bingofancy** [comment]
thank you very much
