### ISSUE TITLE
Trying to import curve_fit from scipy.optimize fails

### ISSUE THREAD

**Issue by cantao** [its-pointless/gcc_termux#85]
When doing
`from scipy.optimize import curve_fit`
I obtained the following error:
`ImportError: dlopen failed: cannot locate symbol "__aeabi_f2lz" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scipy-1.4.1-py3.8-linux-armv8l.egg/scipy/fft/_pocketfft/pypocketfft.cpython-38.so"...`

I'm on Android 9 and have used the script `setup-pointless-repo.sh`, followed by `pkg install scipy`. Both runned flawlessly.

Any hints?

Thank you very much!

**Comment by its-pointless** [comment]
issue is likely caused by me because the android system i compiled it on has that symbol exported in libm.so which it should  be assumed since that shouldn't be visible. 
so it means i should probably recompile it with  --exclude-libs=libgcc.a

**Comment by cantao** [comment]
Thanks for the quick response! I resorted to an old version of scipy (1.3 I guess) and dpkg. Whenever you compile a new version, I'm willing to test it!

Thanks a lot!

**Comment by its-pointless** [comment]
new ver available

**Comment by its-pointless** [comment]
what was happening was /system/lib/libm.so had exported symbols normally found in libgcc.a so i compiled and linked against the libm.so found in ndk. This only appears to only be an issue in gcc not clang.

**Comment by cantao** [comment]
Worked flawlesly! Thank you very much! S2
