### ISSUE TITLE
r-base libicu65 dependency issue

### ISSUE THREAD

**Issue by PG989** [its-pointless/gcc_termux#88]
R returns an error when trying to run:
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library "libicuuc.so.65" not found

Could you please investigate it? 
Thank you in advance.

**Comment by its-pointless** [comment]
updated android-7 repo a few days ago. Which url are you using for it? 
should be `deb https://its-pointless.github.io/files/24 termux extras`
Are you using android-5 or android -6?

**Comment by PG989** [comment]
It is working with your link.
I have followed a not actualized description:
https://conr.ca/post/installing-r-on-android-via-termux/

(I am using android-7)

Thank you.

its-pointless <notifications@github.com> ezt írta (időpont: 2020. márc.
22., V 21:40):

**Comment by SugarRayLua** [comment]
Hi, @its-pointless, is your repo still up? I'm on Android 11 and tried to install R by following also the conr.ca link and had the same problem. I tried to go to your other posted link above that ended in termux extras but that link didn't seem to be working. Thanks!

**Comment by anas140223** [comment]
I having a same problem any of you link is not working
