### ISSUE TITLE
Seems to lack liboctave

### ISSUE THREAD

**Issue by alain2** [its-pointless/gcc_termux#9]
Hello, 

thanks for this work.

I have tried to install octave but I get liboctinterp.so not found, so it seems to lack the liboctave package.

Thanks

**Comment by its-pointless** [comment]
how did you install and which arch arm or aarch64?

**Comment by alain2** [comment]
I use arm and install it by downloading the packets and install them with dpgk in termux.
I have also tried to add
deb [arch=all,arm trusted=yes] https://github.com/its-pointless/its-pointless.g
ithub.io/tree/master/files/ termux extras
in termux source.list

**Comment by its-pointless** [comment]
whats missing is likely a symlink so liboctinterp.so is not in LD_LIBRARY_PATH variable ... its likely iv screwed up a few times here due to transitioning to libc++ library all at once. Iv gotten sloppy and haven't tested.

**Comment by alain2** [comment]
Sorry : there is /data/data/com.termux/files/usr/lib/octave/4.2.1/liboctinterp.so
and LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
but I get
CANNOT LINK EXECUTABLE "octave-cli": library "liboctinterp.so" not found
or
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-4.2.1": library "liboctinterp.so" not found
so what symlink should I add ?

**Comment by alain2** [comment]
I have create in /data/data/com.termux/files/usr/lib
liboctave.so -> octave/4.2.1/liboctave.so
and
liboctinterp.so -> octave/4.2.1/liboctinterp.so
now I get 
CANNOT LINK EXECUTABLE "octave-cli": library "libGraphicsMagick++.so" not found

**Comment by alain2** [comment]
Sorry I have add the package graphicsmagick++_1.3.25-2_arm.deb to remove the "libGraphicsMagick++.so" not found
but now I get 
CANNOT LINK EXECUTABLE "octave-cli": cannot locate symbol "_ZN6Magick5Image9attributeESs" referenced by "/data/data/com.termux/files/usr/lib/octave/4.2.1/liboctinterp.so"...

**Comment by its-pointless** [comment]
you are trying to link old packages remove everything and even then it probably won't work for now seeing as im find little other things.

**Comment by its-pointless** [comment]
Octave is working again its in the repo. You can add my repo using this script https://github.com/its-pointless/gcc_termux/blob/master/setup-pointless-repo.sh

**Comment by alain2** [comment]
yes it works ! Thanks a lot.
