### ISSUE TITLE
R httpuv installation fails

### ISSUE THREAD

**Issue by tmakowski** [its-pointless/gcc_termux#92]
I am having trouble installing `httpuv` package. I have tried installing it from CRAN but it failed. Then I tried both of those https://github.com/its-pointless/gcc_termux/issues/54 and https://github.com/its-pointless/its-pointless.github.io/issues/30 suggestions but neither worked.

The CRAN installation fails at  `testing if installed package can be loaded from temporary location`. The error is due to `dlopen failed: cannot locate symbol "uv__pthread_sigmask"`.

Solution provided in the issues provided above result in an error due to `multiple definition of 'uv_loadavg'` in the clang linker command.

Do you have any suggestions on how to solve this issue?

**Comment by its-pointless** [comment]
iv updated R. so try again or something?
i installed httpuv but it required patching the later package before installing it.

**Comment by its-pointless** [comment]
i updated httpuv and added later patches in R-patches dir https://github.com/its-pointless/gcc_termux/tree/master/R-patches

**Comment by mike-lawrence** [comment]
For posterity, here's the code needed to get the packages & patches, apply them, install dependencies, then the packages:
```bash
curl -O -J https://cloud.r-project.org/src/contrib/later_1.1.0.1.tar.gz
curl -O -J https://cloud.r-project.org/src/contrib/httpuv_1.5.4.tar.gz
curl -O -J https://raw.githubusercontent.com/its-pointless/gcc_termux/master/R-patches/httpuv.patch
curl -O -J https://raw.githubusercontent.com/its-pointless/gcc_termux/master/R-patches/later-tincythread.h.patch 
tar -xf later_1.1.0.1.tar.gz
tar -xf httpuv_1.5.4.tar.gz
patch -p1 < ./httpuv.patch
cd later
patch -p1 < ../later-tincythread.h.patch 
cd ..
R --vanilla -e 'devtools::install_deps("later", repos="https://cloud.r-project.org")'
R CMD INSTALL later
R --vanilla -e 'devtools::install_deps("httpuv", repos="https://cloud.r-project.org")'
R CMD INSTALL httpuv
```
