### ISSUE TITLE
Julia package out of date

### ISSUE THREAD

**Issue by freemin7** [its-pointless/gcc_termux#93]
Julia 1.4.2 has been released for almost two months and Julia 1.5 looks to well on it's way.
There is no pressure to immediately fix this but  it might be something to keep an eye on.

**Comment by its-pointless** [comment]
im updating it now. I had almost done it yesterday but i messed up the packaging.

**Comment by freemin7** [comment]
Thanks for being so responsive.

**Comment by freemin7** [comment]
Are you waiting for 1.5?

**Comment by its-pointless** [comment]
its 1.4.2 right now but arm version of 1.5.0 is not building so i am testing.
