### ISSUE TITLE
libicu version problem

### ISSUE THREAD

**Issue by zcatav** [its-pointless/gcc_termux#97]
After updating libicu to version 67, R not works with following error:
`> R
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library "libicuuc.so.66" not found

> pkg search libicu
Checking availability of current mirror: ok
Sorting... Done
Full Text Search... Done
libicu/stable,now 67.1 aarch64 [installed]
  International Components for Unicode library

`libicu-static/stable 67.1 aarch64
  Static libraries for libicu`

> pkg search r-base
Checking availability of current mirror: ok
Sorting... Done
Full Text Search... Done
r-base/termux,now 4.0.2-1 aarch64 [installed]
  a freely available language and environment for statistical computing and graphics

`Android 10 on a Pixel phone.`

**Comment by zcatav** [comment]
Issue resolved after r-base upgrades to 4.0.2-2.

**Comment by zcatav** [comment]
R opens but when  I run a command following error occurs.

source("covideu.R")
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/curl/libs/curl.so':
  dlopen failed: library "libicuuc.so.66" not found

**Comment by zcatav** [comment]
Solved.

**Comment by zcatav** [comment]
Hi,
I've some problems with update.

Update ends with following errors;

------------------------------
update.packages()

Selection: 1
trying URL 'https://cloud.r-project.org/src/contrib/dplyr_1.0.2.tar.gz'
Content type 'application/x-gzip' length 935654 bytes (913 KB)
==================================================
downloaded 913 KB

trying URL 'https://cloud.r-project.org/src/contrib/fs_1.5.0.tar.gz'
Content type 'application/x-gzip' length 796244 bytes (777 KB)
==================================================
downloaded 777 KB

trying URL 'https://cloud.r-project.org/src/contrib/pkgbuild_1.1.0.tar.gz'
Content type 'application/x-gzip' length 29854 bytes (29 KB)
==================================================
downloaded 29 KB

trying URL 'https://cloud.r-project.org/src/contrib/rvest_0.3.6.tar.gz'
Content type 'application/x-gzip' length 2806156 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

trying URL 'https://cloud.r-project.org/src/contrib/tidyr_1.1.1.tar.gz'
Content type 'application/x-gzip' length 879411 bytes (858 KB)
==================================================
downloaded 858 KB

* installing *source* package ‘dplyr’ ...
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c filter.cpp -o filter.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c funs.cpp -o funs.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c group_by.cpp -o group_by.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c group_data.cpp -o group_data.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c imports.cpp -o imports.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c init.cpp -o init.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c mutate.cpp -o mutate.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c slice.cpp -o slice.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG   -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c summarise.cpp -o summarise.o
g++ -std=gnu++11 -shared -L/data/data/com.termux/files/usr/lib/R/lib -L/data/data/com.termux/files/usr/lib -landroid-support -lm -lgfortran -lopenblas -landroid-glob -liconv -llzma -ljpeg -lpng -licuuc -licudata -latomic -lcompiler_rt -o dplyr.so filter.o funs.o group_by.o group_data.o imports.o init.o mutate.o slice.o summarise.o -L/data/data/com.termux/files/usr/lib/R/lib -lR
installing to /data/data/com.termux/files/usr/lib/R/library/00LOCK-dplyr/00new/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/glue/libs/glue.so':
  dlopen failed: library "libicuuc.so.66" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘dplyr’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/dplyr’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/dplyr’
* installing *source* package ‘fs’ ...
** package ‘fs’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c dir.cc -o dir.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c error.cc -o error.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c file.cc -o file.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c fs.cc -o fs.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c getmode.cc -o getmode.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c id.cc -o id.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG -I./libuv-1.38.1/include -I. -pthread  -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c init.cc -o init.o
id.cc:109:17: error: use of undeclared
      identifier 'getpwent'; did you mean
      'getgrent'?
  passwd* pwd = getpwent();
                ^~~~~~~~
                getgrent
/data/data/com.termux/files/usr/include/grp.h:55:22: note:
      'getgrent' declared here
static struct group* getgrent(void) { ...
                     ^
id.cc:109:11: error: cannot initialize a
      variable of type 'passwd *' with an
      rvalue of type 'struct group *'
  passwd* pwd = getpwent();
          ^     ~~~~~~~~~~
id.cc:113:11: error: use of undeclared
      identifier 'getpwent'; did you mean
      'getgrent'?
    pwd = getpwent();
          ^~~~~~~~
          getgrent
/data/data/com.termux/files/usr/include/grp.h:55:22: note:
      'getgrent' declared here
static struct group* getgrent(void) { ...
                     ^
3 errors generated.
make: *** [/data/data/com.termux/files/usr/lib/R/etc/Makeconf:172: id.o] Error 1
make: *** Waiting for unfinished jobs....
ERROR: compilation failed for package ‘fs’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/fs’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/fs’
* installing *source* package ‘pkgbuild’ ...
** package ‘pkgbuild’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/processx/libs/processx.so':
  dlopen failed: library "libicuuc.so.66" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘pkgbuild’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/pkgbuild’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/pkgbuild’
* installing *source* package ‘rvest’ ...
** package ‘rvest’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for ‘xml2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/xml2/libs/xml2.so':
  dlopen failed: library "libicuuc.so.66" not found
Error: package ‘xml2’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘rvest’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/rvest’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/rvest’
* installing *source* package ‘tidyr’ ...
** package ‘tidyr’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG  -I'/data/data/com.termux/files/usr/lib/R/library/cpp11/include' -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c cpp11.cpp -o cpp11.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG  -I'/data/data/com.termux/files/usr/lib/R/library/cpp11/include' -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c fill.cpp -o fill.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG  -I'/data/data/com.termux/files/usr/lib/R/library/cpp11/include' -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c melt.cpp -o melt.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG  -I'/data/data/com.termux/files/usr/lib/R/library/cpp11/include' -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c simplifyPieces.cpp -o simplifyPieces.o
g++ -std=gnu++11 -shared -L/data/data/com.termux/files/usr/lib/R/lib -L/data/data/com.termux/files/usr/lib -landroid-support -lm -lgfortran -lopenblas -landroid-glob -liconv -llzma -ljpeg -lpng -licuuc -licudata -latomic -lcompiler_rt -o tidyr.so cpp11.o fill.o melt.o simplifyPieces.o -L/data/data/com.termux/files/usr/lib/R/lib -lR
installing to /data/data/com.termux/files/usr/lib/R/library/00LOCK-tidyr/00new/tidyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/glue/libs/glue.so':
  dlopen failed: library "libicuuc.so.66" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘tidyr’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/tidyr’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/tidyr’

The downloaded source packages are in
        ‘/data/data/com.termux/files/usr/tmp/RtmpfycggN/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘dplyr’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘fs’ had non-zero exit status
3: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘pkgbuild’ had non-zero exit status
4: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘rvest’ had non-zero exit status
5: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘tidyr’ had non-zero exit status
-------------------------

glue is already installed. R is upgraded from 3.x to 4.x. Termux is upgraded latest from f-droid.

Thanks for your attention.

**Comment by its-pointless** [comment]
update should fix this.

**Comment by zcatav** [comment]
Hi,
Latest update attempting results as follows.


trying URL 'https://cloud.r-project.org/src/contrib/fs_1.5.0.tar.gz'
Content type 'application/x-gzip' length 796244 bytes (777 KB)
==================================================
downloaded 777 KB

trying URL 'https://cloud.r-project.org/src/contrib/processx_3.4.4.tar.gz'
Content type 'application/x-gzip' length 134703 bytes (131 KB)
==================================================
downloaded 131 KB

* installing *source* package ‘fs’ ...
** package ‘fs’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c dir.cc -o
dir.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c error.cc -o
error.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c file.cc -o
file.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c fs.cc -o fs.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c getmode.cc -o
getmode.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c id.cc -o id.o
g++ -std=gnu++11 -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
-I./libuv-1.38.1/include -I. -pthread
-I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c init.cc -o
init.o
id.cc:109:17: error: use of undeclared
      identifier 'getpwent'; did you mean
      'getgrent'?
  passwd* pwd = getpwent();
                ^~~~~~~~
                getgrent
/data/data/com.termux/files/usr/include/grp.h:55:22: note:
      'getgrent' declared here
static struct group* getgrent(void) { ...
                     ^
id.cc:109:11: error: cannot initialize a
      variable of type 'passwd *' with an
      rvalue of type 'struct group *'
  passwd* pwd = getpwent();
          ^     ~~~~~~~~~~
id.cc:113:11: error: use of undeclared
      identifier 'getpwent'; did you mean
      'getgrent'?
    pwd = getpwent();
          ^~~~~~~~
          getgrent
/data/data/com.termux/files/usr/include/grp.h:55:22: note:
      'getgrent' declared here
static struct group* getgrent(void) { ...
                     ^
3 errors generated.
make: *** [/data/data/com.termux/files/usr/lib/R/etc/Makeconf:172: id.o]
Error 1
make: *** Waiting for unfinished jobs....
ERROR: compilation failed for package ‘fs’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/fs’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/fs’
* installing *source* package ‘processx’ ...
** package ‘processx’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -g -O2  -Wall tools/px.c -o tools/px
gcc -g -O2  supervisor/supervisor.c supervisor/utils.c \
      -o supervisor/supervisor
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c base64.c -o
base64.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c client.c -o
client.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c errors.c -o
errors.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c init.c -o
init.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c poll.c -o
poll.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
processx-connection.c -o processx-connection.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
processx-vector.c -o processx-vector.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
create-time.c -o create-time.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
unix/childlist.c -o unix/childlist.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
unix/connection.c -o unix/connection.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
unix/processx.c -o unix/processx.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
unix/sigchld.c -o unix/sigchld.o
unix/sigchld.c:6:44: warning: braces around
      scalar initializer
      [-Wbraced-scalar-init]
  ...sigaction old_sig_handler = {{ 0 }};
                                  ^~~~~
1 warning generated.
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c unix/utils.c
-o unix/utils.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c
unix/named_pipe.c -o unix/named_pipe.o
gcc -I"/data/data/com.termux/files/usr/lib/R/include" -DNDEBUG
 -I/data/data/com.termux/files/usr/include   -fpic  -g -O2  -c cleancall.c
-o cleancall.o
gcc -shared -L"/data/data/com.termux/files/usr/lib/R/lib"
-L/data/data/com.termux/files/usr/lib -landroid-support -lm -lgfortran
-lopenblas -landroid-glob -liconv -llzma -ljpeg -lpng -licuuc -licudata
-latomic -lcompiler_rt  -o client.so base64.o client.o errors.o
 -L"/data/data/com.termux/files/usr/lib/R/lib" -lR
gcc -shared -L/data/data/com.termux/files/usr/lib/R/lib
-L/data/data/com.termux/files/usr/lib -landroid-support -lm -lgfortran
-lopenblas -landroid-glob -liconv -llzma -ljpeg -lpng -licuuc -licudata
-latomic -lcompiler_rt -o processx.so init.o poll.o errors.o
processx-connection.o processx-vector.o create-time.o base64.o
unix/childlist.o unix/connection.o unix/processx.o unix/sigchld.o
unix/utils.o unix/named_pipe.o cleancall.o
-L/data/data/com.termux/files/usr/lib/R/lib -lR
installing via 'install.libs.R' to
/data/data/com.termux/files/usr/lib/R/library/00LOCK-processx/00new/processx
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘processx’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: ps::ps_handle()
  error: Unknown errorfs_error0NA
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/data/data/com.termux/files/usr/lib/R/library/processx’
* restoring previous
‘/data/data/com.termux/files/usr/lib/R/library/processx’

The downloaded source packages are in
        ‘/data/data/com.termux/files/usr/tmp/Rtmpw5cbNo/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages(update[instlib == l, "Package"], l, contriburl =
contriburl,  :
  installation of package ‘fs’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, contriburl =
contriburl,  :
  installation of package ‘processx’ had non-zero exit status


7 Eyl 2020 Pzt 04:03 tarihinde its-pointless <notifications@github.com>
şunu yazdı:

**Comment by zcatav** [comment]
My latest error about update.
