### ISSUE TITLE
OpenCV python script with face recognition fails in Termux after Protocol Buffer update

### ISSUE THREAD

**Issue by benedictbabu** [its-pointless/gcc_termux#98]
**Problem description**

OpenCV python script with face recognition fails in Termux after Protocol Buffer shared library was updated during, Termux rolling update. OpenCV still links to the old library. The script was working without any errors before the update, with the compiled version 3.12.2.
Is there any link to the 3.12.2 version to so that it can be replaced/compiled ?

**Expected behavior**

The script starts to run in the environment.

**Additional information**

****[libprotobuf FATAL /home/builder/termux-packages/.termux-builder/libprotobuf/src/src/google/protobuf/stubs/common.cc:87] This program was compiled against version 3.12.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.13.0). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "modules/dnn/opencv-caffe.pb.cc".)
terminating with uncaught exception of type google::protobuf::FatalException: This program was compiled against version 3.12.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.13.0). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "modules/dnn/opencv-caffe.pb.cc".)**
Aborted**

Device Used      : Samsung Galaxy Tab A 8.0 (2019)
OS Version         : Android 9.0 (Pie)

```

```

**Comment by anuragjk** [comment]
i have a similar issue.

**Comment by its-pointless** [comment]
ok i fix

**Comment by its-pointless** [comment]
should be fixed
